eclipse-vertx/vertx-sql-client

src/main/java/com/julienviet/pgclient/codec/encoder/MessageEncoder.java
src/main/java/com/julienviet/pgclient/codec/encoder/message/Execute.java
src/main/java/com/julienviet/pgclient/impl/DbConnection.java

Removes statement in the execute message and switch portal in the encoder

Encoder fixes

---

src/main/java/com/julienviet/pgclient/impl/PostgresSQLConnection.java

Fixes unimplemented `setOptions` for `SQLConnection`

Impl options

---

src/main/java/com/julienviet/pgclient/codec/encoder/MessageEncoder.java
src/main/java/com/julienviet/pgclient/codec/encoder/message/CancelRequest.java
src/main/java/com/julienviet/pgclient/codec/encoder/message/SSLRequest.java

Add SSLRequest and CancelRequest messages

---

src/main/asciidoc/dataobjects.adoc
src/main/asciidoc/groovy/index.adoc
src/main/asciidoc/java/index.adoc
src/main/asciidoc/js/index.adoc
src/main/asciidoc/kotlin/index.adoc
src/main/asciidoc/ruby/index.adoc
src/main/generated/com/julienviet/pgclient/PgNotificationConverter.java
src/main/java/com/julienviet/pgclient/PgConnection.java
src/main/java/com/julienviet/pgclient/PgNotification.java
src/main/java/com/julienviet/pgclient/impl/Connection.java
src/main/java/com/julienviet/pgclient/impl/ConnectionPool.java
src/main/java/com/julienviet/pgclient/impl/PgConnectionImpl.java
src/main/java/com/julienviet/pgclient/impl/PgPoolImpl.java
src/main/java/com/julienviet/pgclient/impl/SocketConnection.java
src/main/java/com/julienviet/pgclient/impl/pubsub/PgSubscriberImpl.java
src/main/java/com/julienviet/pgclient/package-info.java
src/main/java/com/julienviet/pgclient/pubsub/PgChannel.java
src/main/java/com/julienviet/pgclient/pubsub/PgSubscriber.java
src/main/java/examples/Examples.java
src/main/kotlin/com/julienviet/kotlin/pgclient/PgNotification.kt
src/test/java/com/julienviet/pgclient/PubSubTest.java
src/test/java/com/julienviet/pgclient/pool/SimpleHolder.java

@pmlopes I remember you were interested by this feature, can you have a brief look ?

Pub-sub support - fixes #36

---

src/main/java/com/julienviet/pgclient/impl/codec/DataType.java
src/test/java/com/julienviet/pgclient/DataTypeBinaryTest.java
src/test/resources/create-postgres.sql

Fixes https://github.com/vietj/reactive-pg-client/issues/50

Fix binary decode/encode character types

---

src/main/java/com/julienviet/pgclient/Row.java
src/main/java/com/julienviet/pgclient/Tuple.java
src/main/java/com/julienviet/pgclient/impl/ArrayTuple.java
src/main/java/com/julienviet/pgclient/impl/RowImpl.java
src/main/java/com/julienviet/pgclient/impl/codec/DataType.java
src/test/java/com/julienviet/pgclient/DataTypeBinaryTest.java
src/test/java/com/julienviet/pgclient/DataTypeTextTest.java

Fixes https://github.com/vietj/reactive-pg-client/issues/53

Supports UUID data type

---

README.adoc
src/main/java/com/julienviet/pgclient/impl/codec/DataType.java
src/test/java/com/julienviet/pgclient/DataTypeBinaryTest.java

can you review this @EmadAlblueshi ?

Bytea binary support - fixes #64

---

src/main/java/com/julienviet/pgclient/Row.java
src/main/java/com/julienviet/pgclient/Tuple.java
src/main/java/com/julienviet/pgclient/impl/ArrayTuple.java
src/main/java/com/julienviet/pgclient/impl/RowImpl.java
src/main/java/com/julienviet/pgclient/impl/codec/DataType.java
src/test/java/com/julienviet/pgclient/DataTypeTextTest.java

Fixes https://github.com/vietj/reactive-pg-client/issues/61
@vietj would you please review ?

Support BigDecimal for NUMERIC (Text) data type

---

src/main/java/io/reactiverse/pgclient/Numeric.java
src/main/java/io/reactiverse/pgclient/Row.java
src/main/java/io/reactiverse/pgclient/Tuple.java
src/main/java/io/reactiverse/pgclient/impl/ArrayTuple.java
src/main/java/io/reactiverse/pgclient/impl/RowImpl.java
src/test/java/io/reactiverse/pgclient/ColumnChecker.java
src/test/java/io/reactiverse/pgclient/DataTypeBinaryTest.java
src/test/java/io/reactiverse/pgclient/DataTypeTextTest.java
src/test/java/io/reactiverse/pgclient/NumericTest.java
src/test/java/io/reactiverse/pgclient/RowTest.java
src/test/java/io/reactiverse/pgclient/TupleTest.java

Fix the issue https://github.com/reactiverse/reactive-pg-client/issues/84. Please correct me if I leave behind anything.

Add API support for short data type - fixes #84 

---

src/main/docs/index.md
src/main/java/io/reactiverse/pgclient/PgConnectOptions.java
src/main/java/io/reactiverse/pgclient/package-info.java

See the issue https://github.com/reactiverse/reactive-pg-client/issues/39.
Supported Environment Variables:
* PGHOST
* PGHOSTADDR
* PGPORT
* PGDATABASE
* PGUSER
* PGPASSWORD

Provide the ability to configure from env variable

---

src/main/docs/index.md
src/main/java/examples/Examples.java
src/main/java/io/reactiverse/pgclient/impl/PgConnectionUriParser.java
src/main/java/io/reactiverse/pgclient/package-info.java

See https://github.com/reactiverse/reactive-pg-client/issues/96.

Documentation improvements - fix issue #96

---

README.adoc
src/main/docs/index.md
src/main/java/io/reactiverse/pgclient/impl/codec/DataType.java
src/main/java/io/reactiverse/pgclient/impl/codec/DataTypeCodec.java
src/test/java/io/reactiverse/pgclient/DataTypeExtendedEncodingTest.java
src/test/java/io/reactiverse/pgclient/DataTypeSimpleEncodingTest.java
src/test/resources/create-postgres.sql

Fixes https://github.com/reactiverse/reactive-pg-client/issues/57

Enum data type support

---

README.adoc
src/main/docs/index.md
src/main/java/io/reactiverse/pgclient/Row.java
src/main/java/io/reactiverse/pgclient/Tuple.java
src/main/java/io/reactiverse/pgclient/data/Interval.java
src/main/java/io/reactiverse/pgclient/impl/ArrayTuple.java
src/main/java/io/reactiverse/pgclient/impl/RowImpl.java
src/main/java/io/reactiverse/pgclient/impl/codec/DataType.java
src/main/java/io/reactiverse/pgclient/impl/codec/DataTypeCodec.java
src/main/java/io/reactiverse/pgclient/impl/codec/encoder/MessageEncoder.java
src/main/java/io/reactiverse/pgclient/impl/codec/encoder/StartupMessage.java
src/test/java/io/reactiverse/pgclient/DataTypeExtendedEncodingTest.java
src/test/java/io/reactiverse/pgclient/DataTypeSimpleEncodingTest.java
src/test/resources/create-postgres.sql

Addresses https://github.com/reactiverse/reactive-pg-client/issues/125

Supports interval data type

---

src/main/java/io/reactiverse/pgclient/Row.java
src/main/java/io/reactiverse/pgclient/Tuple.java
src/main/java/io/reactiverse/pgclient/impl/ArrayTuple.java
src/main/java/io/reactiverse/pgclient/impl/RowImpl.java
src/test/java/io/reactiverse/pgclient/RowTest.java

This is an enhancement for #135

Supports getting column name from Row

---

docker/postgres/resources/create-postgres.sql
docker/postgres_tc/create-postgres.sql
src/main/java/io/reactiverse/pgclient/impl/codec/DataTypeCodec.java
src/test/java/io/reactiverse/pgclient/PgClientTestBase.java

A JSON column can be nullable, so a null value must be accepted

Accept null value for json parameter

---

src/main/docs/index.md
src/main/java/examples/Examples.java

fixes https://github.com/reactiverse/reactive-pg-client/issues/122.

Add documentation and an example for fetching generated keys - fixes #122

---

README.adoc
src/main/docs/index.md
src/main/java/examples/Examples.java
src/main/java/io/reactiverse/pgclient/PgClient.java
src/main/java/io/reactiverse/pgclient/PgConnection.java
src/main/java/io/reactiverse/pgclient/PgPool.java
src/main/java/io/reactiverse/pgclient/impl/Connection.java
src/main/java/io/reactiverse/pgclient/impl/ConnectionPool.java
src/main/java/io/reactiverse/pgclient/impl/InitCommand.java
src/main/java/io/reactiverse/pgclient/impl/PgConnectionImpl.java
src/main/java/io/reactiverse/pgclient/impl/PgPoolImpl.java
src/main/java/io/reactiverse/pgclient/impl/SocketConnection.java
src/test/java/io/reactiverse/pgclient/PgConnectionTest.java
src/test/java/io/reactiverse/pgclient/PgPoolTestBase.java
src/test/java/io/reactiverse/pgclient/pool/SimpleConnection.java

Add support for request cancellation - fixes https://github.com/reactiverse/reactive-pg-client/issues/37.

Request cancellation support

---

src/test/java/io/reactiverse/pgclient/PgTransactionTest.java

Add two test cases for #237. And I tried these two cases could pass with current code. This issue might have been fixed somewhere.

add testcases for #237.

---

src/main/java/io/vertx/pgclient/impl/codec/DataTypeCodec.java
src/test/java/io/vertx/pgclient/data/BinaryDataTypesSimpleCodecTest.java

fix https://github.com/eclipse-vertx/vertx-sql-client/issues/234.

Add support for Postgres BYTEA escape format

---

pom.xml
src/main/asciidoc/dataobjects.adoc
src/main/kotlin/io/vertx/kotlin/pgclient/PgConnectOptions.kt
src/main/kotlin/io/vertx/kotlin/pgclient/PgConnection.kt
src/main/kotlin/io/vertx/kotlin/pgclient/PgNotification.kt
src/main/kotlin/io/vertx/kotlin/pgclient/PgPool.kt
src/main/kotlin/io/vertx/kotlin/pgclient/PgPoolOptions.kt
src/main/kotlin/io/vertx/kotlin/pgclient/data/Box.kt
src/main/kotlin/io/vertx/kotlin/pgclient/data/Circle.kt
src/main/kotlin/io/vertx/kotlin/pgclient/data/Interval.kt
src/main/kotlin/io/vertx/kotlin/pgclient/data/Line.kt
src/main/kotlin/io/vertx/kotlin/pgclient/data/LineSegment.kt
src/main/kotlin/io/vertx/kotlin/pgclient/data/Path.kt
src/main/kotlin/io/vertx/kotlin/pgclient/data/Point.kt
src/main/kotlin/io/vertx/kotlin/pgclient/data/Polygon.kt
src/main/kotlin/io/vertx/kotlin/pgclient/pubsub/PgChannel.kt
src/main/kotlin/io/vertx/kotlin/pgclient/pubsub/PgSubscriber.kt
src/main/kotlin/io/vertx/kotlin/sqlclient/Cursor.kt
src/main/kotlin/io/vertx/kotlin/sqlclient/Pool.kt
src/main/kotlin/io/vertx/kotlin/sqlclient/PreparedQuery.kt
src/main/kotlin/io/vertx/kotlin/sqlclient/SqlClient.kt
src/main/kotlin/io/vertx/kotlin/sqlclient/SqlConnection.kt
src/main/kotlin/io/vertx/kotlin/sqlclient/Transaction.kt

Upgrade Vert.x to 3.7.1

---

src/main/java/io/vertx/mysqlclient/impl/MySQLRowImpl.java
src/main/java/io/vertx/mysqlclient/impl/codec/CloseConnectionCommandCodec.java
src/main/java/io/vertx/mysqlclient/impl/codec/CloseStatementCommandCodec.java
src/main/java/io/vertx/mysqlclient/impl/codec/CommandCodec.java
src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandCodec.java
src/main/java/io/vertx/mysqlclient/impl/codec/InitCommandCodec.java
src/main/java/io/vertx/mysqlclient/impl/codec/MySQLDecoder.java
src/main/java/io/vertx/mysqlclient/impl/codec/PrepareStatementCodec.java
src/main/java/io/vertx/mysqlclient/impl/codec/ResetStatementCommandCodec.java
src/main/java/io/vertx/mysqlclient/impl/codec/SimpleQueryCommandCodec.java
src/main/java/io/vertx/mysqlclient/impl/codec/datatype/DataType.java
src/test/java/io/vertx/mysqlclient/MySQLQueryTest.java
src/test/java/io/vertx/mysqlclient/junit/MySQLRule.java

Add support for MySQL 16MBytes+ size packet codecs

---

vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnection.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLSetOption.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionImpl.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ChangeUserCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/CloseConnectionCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/CloseStatementCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/CommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/DebugCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/InitDbCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLEncoder.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/PingCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ResetConnectionCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ResetStatementCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/SetOptionCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/StatisticsCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/command/ChangeUserCommand.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/command/DebugCommand.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/command/InitDbCommand.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/command/PingCommand.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/command/ResetConnectionCommand.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/command/SetOptionCommand.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/command/StatisticsCommand.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/protocol/CommandType.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLUtilityCommandTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/junit/MySQLRule.java

Add support for MySQL utility commands

---

vertx-mysql-client/src/main/asciidoc/index.adoc
vertx-mysql-client/src/main/java/examples/MySQLClientExamples.java

Initial work for MySQL documentation, related to #317.

MySQL documentation

---

vertx-mysql-client/README.adoc
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLRowImpl.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLQueryTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/DateTimeBinaryCodecTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/DateTimeTextCodecTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/MySQLDataTypeTestBase.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/StringDataTypeTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLBinaryDataTypeDecodeTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLBinaryDataTypeEncodeTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLTextDataTypeDecodeTest.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/BinaryDataTypeDecodeTestBase.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/BinaryDataTypeEncodeTestBase.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/PreparedQueryTestBase.java

* add support for getting value by class type in MySQL row
* MySQL datatype tests improvements
* TCK tests improvements

MySQL row improvements

---

vertx-pg-client/README.adoc
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/RowImpl.java
vertx-pg-client/src/test/java/io/vertx/pgclient/data/JsonTypesExtendedCodecTest.java

Fix #323 and add support for get value by type in Postgres Row for the non geometric data types.

Fix the CI and improvements for Postgres RowImpl

---

vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionImpl.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLPoolImpl.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/SimpleQueryCommandCodec.java

so that the MySQL client will not hang or meet unexpected behaviors.

Improve unsupported operation failure handling for MySQL

---

vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnection.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionFactory.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionImpl.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLPoolImpl.java

MySQL closehook support

---

vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionImpl.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLPoolImpl.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedBatchQueryCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandBaseCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLEncoder.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/QueryCommandBaseCodec.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLPreparedBatchTest.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PreparedBatchTest.java
vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgPreparedBatchTest.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/PreparedBatchTestBase.java

MySQL prepared batch support

---

vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataType.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataTypeCodec.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/SimpleQueryCodec.java

Postgres logging minors

---

vertx-mysql-client/src/main/asciidoc/index.adoc
vertx-mysql-client/src/main/java/examples/MySQLClientExamples.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnectOptions.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnection.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLPool.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionUriParser.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLConnectOptionsProviderTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLConnectionUriParserTest.java
vertx-pg-client/src/main/asciidoc/index.adoc
vertx-pg-client/src/main/java/examples/PgClientExamples.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionUriParser.java

also improve the configuration documentation and connection uri parser for Postgres, this fixes #337

MySQL Connection Uri support

---

vertx-mysql-client/src/main/asciidoc/dataobjects.adoc
vertx-mysql-client/src/main/asciidoc/index.adoc
vertx-mysql-client/src/main/java/examples/MySQLClientExamples.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnectOptions.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionFactory.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionImpl.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionUriParser.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLSocketConnection.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ChangeUserCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/InitCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/command/ChangeUserCommand.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLConnectOptionsProviderTest.java
vertx-pg-client/src/main/asciidoc/dataobjects.adoc
vertx-pg-client/src/main/asciidoc/index.adoc
vertx-pg-client/src/main/java/examples/PgClientExamples.java
vertx-pg-client/src/main/java/io/vertx/pgclient/PgConnectOptions.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionFactory.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionUriParser.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgSocketConnection.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/InitCommandCodec.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgEncoder.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/StartupMessage.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectOptionsProviderTest.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectionTest.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectionUriParserTest.java
vertx-sql-client/src/main/asciidoc/dataobjects.adoc
vertx-sql-client/src/main/generated/io/vertx/sqlclient/SqlConnectOptionsConverter.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/SqlConnectOptions.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/command/InitCommand.java

support for both MySQL and PostgreSQL, for MySQL we can provide an option to configure the connection attributes, for PostgreSQL we can provide an option to configure the generic properties, this will also fix #243.

Add support for configuring properties

---

.travis.yml
vertx-mysql-client/README.adoc
vertx-mysql-client/src/main/asciidoc/index.adoc
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/CommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedBatchQueryCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandBaseCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/InitCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLEncoder.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/PrepareStatementCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/QueryCommandBaseCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/SimpleQueryCommandCodec.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLQueryTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLUtilityCommandTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/junit/MySQLRule.java

This will fix #355 , fix #354 .

Build matrix for MySQL and make client compatible with MySQL 5.6

---

vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionUriParser.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLConnectionUriParserTest.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionUriParser.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectionUriParserTest.java

Support Mysql ParsingUserInfoContainExclamationMark

---

vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/ArrayTuple.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/impl/TupleTest.java

Add support for tuple accessor methods

---

vertx-pg-client/README.adoc
vertx-pg-client/src/test/java/io/vertx/pgclient/data/TsTypesExtendedCodecTest.java

Fix inconsistency in text search tests

---

vertx-mysql-client/src/main/asciidoc/index.adoc
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLSocketConnection.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLEncoder.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/SimpleQueryCommandCodec.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLQueryTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/junit/MySQLRule.java
vertx-mysql-client/src/test/resources/init.sql

MySQL LOCAL INFILE support

---

vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLPool.java
vertx-pg-client/src/main/java/io/vertx/pgclient/PgPool.java

Signed-off-by: shenzhou-6 <yizmao.me@gmail.com>

Create Pool With vertx connectionUrl and default PoolOptions

---

vertx-mysql-client/src/main/asciidoc/dataobjects.adoc
vertx-mysql-client/src/main/generated/io/vertx/mysqlclient/MySQLConnectOptionsConverter.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnectOptions.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionFactory.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionUriParser.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLSocketConnection.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/InitialHandshakeCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/command/InitialHandshakeCommand.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLClientCapabilitiesTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLConnectOptionsProviderTest.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/PreparedQueryTestBase.java

User can configure how affected rows are counted

---

vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/DataTypeCodec.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/DateTimeBinaryCodecTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/DateTimeTextCodecTest.java

Fix incorrect text decoding MySQL DATETIME type

---

vertx-mysql-client/src/main/asciidoc/index.adoc
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionFactory.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLSocketConnection.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/CapabilitiesFlag.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ChangeUserCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/InitialHandshakeCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLEncoder.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/command/InitialHandshakeCommand.java

Rework capabilities flags

---

vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/TransactionImpl.java

Signed-off-by: Dimitris Zenios <dimitris.zenios@gmail.com>

Fixes #465

---

vertx-mysql-client/src/main/java/examples/MySQLClientExamples.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLClient.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedBatchQueryCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandBaseCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/QueryCommandBaseCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/SimpleQueryCommandCodec.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLQueryTest.java

MySQL lastInsertId should be represented as Long type instead of Integer

---

vertx-mysql-client/src/main/asciidoc/dataobjects.adoc
vertx-mysql-client/src/main/asciidoc/index.adoc
vertx-mysql-client/src/main/generated/io/vertx/mysqlclient/MySQLConnectOptionsConverter.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnectOptions.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLCollation.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionFactory.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLSocketConnection.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ChangeUserCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/DataTypeCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandBaseCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/InitialHandshakeCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLEncoder.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/PrepareStatementCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/RowResultDecoder.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/SimpleQueryCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/StatisticsCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/command/InitialHandshakeCommand.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/util/BufferUtils.java

Fix #447.
This PR also improves the charset processing of MySQL row decoding.

Add support for MySQL characterEncoding option

---

vertx-mysql-client/src/main/asciidoc/index.adoc
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/DataTypeCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/Packets.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/NumericDataTypeTest.java
vertx-mysql-client/src/test/resources/init.sql
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataTypeCodec.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/codec/CommonCodec.java

add support for MySQL unsgined data types

MySQL unsigned numeric data type support

---

vertx-mysql-client/src/main/asciidoc/index.adoc
vertx-mysql-client/src/main/java/examples/MySQLClientExamples.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ColumnDefinition.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/DataType.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/DataTypeCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedBatchQueryCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandBaseCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLParamDesc.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/Packets.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/RowResultDecoder.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLPreparedStatementTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/DateTimeBinaryCodecTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/MySQLDataTypeTestBase.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/NumericDataTypeTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLPreparedQueryCachedTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLPreparedQueryTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLPreparedQueryTestBase.java

MySQL statement rework

---

vertx-mysql-client/src/main/asciidoc/index.adoc
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/DataTypeCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/Packets.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/NumericDataTypeTest.java
vertx-mysql-client/src/test/resources/init.sql
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataTypeCodec.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/codec/CommonCodec.java

MySQL unsigned support for 3.8

---

vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLCollation.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/DataTypeCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/RowResultDecoder.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/StringDataTypeTest.java
vertx-mysql-client/src/test/resources/init.sql

Use collation id instead of BINARY_FLAG to distinguish between binary and nonbinary data

---

vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/InitiateSslHandler.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLEncoder.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLTLSTest.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SocketConnectionBase.java

Get the SSL handshake failure being reported to messageHandler correctly

---

vertx-db2-client/src/main/java/examples/DB2ClientExamples.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/CloseConnectionCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/CloseCursorCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/CloseStatementCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/CommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2Decoder.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2Encoder.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2PreparedStatement.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/ExtendedQueryCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/QueryCommandBaseCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/SimpleQueryCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/Cursor.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAConnectResponse.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryRequest.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryResponse.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2PreparedQueryTestBase.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/PreparedQueryTestBase.java

Implement incremental cursor fetch

---

vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2PreparedQueryCachedTest.java

Fixes #501 
@mswatosh please review

Enable tests in DB2PreparedQueryCachedTest related to incremental cursor fetch

---

vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLTLSTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/junit/MySQLRule.java

backport #533 to `3.9` branch - fixes #532

MySQL TLS testing fix

---

vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2CollectorTest.java

Enable DB2Collector error path tests

---

vertx-mysql-client/src/main/asciidoc/index.adoc

Motivation:
Some best practices and pitfalls when using the Reactive MySQL Client can be summarized as a dedicated section in the documentation.
Conformance:

Add a section of best practices for MySQL

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2Encoder.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2ParamDesc.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2RowDesc.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/SimpleQueryCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/ClientTypes.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/ColumnMetaData.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryResponse.java
vertx-db2-client/src/test/java/io/vertx/db2client/DB2TestBase.java
vertx-db2-client/src/test/java/io/vertx/db2client/GeneratedKeysTest.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/ClientConfig.java

Part of #497 
Builds on top of commits from PR #537

 Support for queries that return auto-generated keys

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2ParamDesc.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/ExtendedBatchQueryCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/ExtendedQueryCommandBaseCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/ExtendedQueryCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/PrepareStatementCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/QueryCommandBaseCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/RowResultDecoder.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/ClientTypes.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/ColumnMetaData.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/CrossConverters.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/Cursor.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryRequest.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDARequest.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/SqlCode.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2BinaryDataTypeDecodeTest.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2BinaryDataTypeEncodeTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLBinaryDataTypeDecodeTest.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/ArrayTuple.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/ListTuple.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/BinaryDataTypeDecodeTestBase.java

Enable binary data type TCK tests

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2SocketConnection.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/CloseConnectionCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/CloseCursorCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2Encoder.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/ExtendedBatchQueryCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/ExtendedQueryCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/InitialHandshakeCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/PingCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/PrepareStatementCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/QueryCommandBaseCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/SimpleQueryCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/CCSIDConstants.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/CodePoint.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/Cursor.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DB2Package.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAConnectRequest.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAConnectResponse.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryRequest.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryResponse.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDARequest.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAResponse.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DatabaseMetaData.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/SectionManager.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/Typdef.java
vertx-db2-client/src/test/java/io/vertx/db2client/junit/DB2Resource.java
vertx-db2-client/src/test/resources/init.zos.sql

Initial support for DB2 on z/OS

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2RowImpl.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2ParamDesc.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/ExtendedBatchQueryCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/ExtendedQueryCommandBaseCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/ExtendedQueryCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/InitialHandshakeCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/PingCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/RowResultDecoder.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/Cursor.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryRequest.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAResponse.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/FloatingPoint.java
vertx-db2-client/src/test/java/io/vertx/db2client/TableJoinTest.java
vertx-db2-client/src/test/java/io/vertx/db2client/junit/DB2Resource.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2BinaryDataTypeDecodeTest.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2BinaryDataTypeEncodeTest.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2TextDataTypeDecodeTest.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2TransactionTest.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/Tuple.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/ArrayTuple.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/ListTuple.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/TupleInternal.java

 Get all DB2 tests passing with DB2 on Z

---

vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLParamDesc.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLRowImpl.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedBatchQueryCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLPreparedStatement.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ResetStatementCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/RowResultDecoder.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/datatype/DataType.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/protocol/ColumnDefinition.java

Motivation:
fixes https://github.com/eclipse-vertx/vertx-sql-client/issues/579.
Conformance:

Rework MySQL prepared statement binding parameters

---

vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnectOptions.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/spi/MySQLDriver.java
vertx-mysql-client/src/main/resources/META-INF/services/io.vertx.sqlclient.spi.Driver
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLDriverTest.java
vertx-pg-client/src/main/java/io/vertx/pgclient/PgConnectOptions.java
vertx-pg-client/src/main/java/io/vertx/pgclient/spi/PgDriver.java
vertx-pg-client/src/main/resources/META-INF/services/io.vertx.sqlclient.spi.Driver
vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgDriverTest.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/Pool.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/SqlConnectOptions.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/spi/Driver.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/DriverTestBase.java

Backport PR #618 (PG and MySQL only)

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/InitialHandshakeCommandCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DB2Package.java

Backport: Reduce initial handshake from 2 server round-trips to 1 round-trip

---

vertx-sql-client/src/main/java/io/vertx/sqlclient/SqlConnectOptions.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/DriverTestBase.java

Backport: Fix NPE in generic connection init path

---

vertx-mssql-client/src/main/asciidoc/index.adoc
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedQueryCommandCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLDataTypeCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/QueryCommandBaseCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/RowResultDecoder.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/SQLBatchCommandCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/datatype/BitNDataType.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/datatype/FloatNDataType.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/datatype/IntNDataType.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLDataTypeTestBase.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLFullDataTypeTestBase.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLNotNullableDataTypeTestBase.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLNullableDataTypeTestBase.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNotNullableDataTypeTest.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNullableDataTypeTest.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLQueryNotNullableDataTypeTest.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLQueryNullableDataTypeTest.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/tck/MSSQLBinaryDataTypeDecodeTest.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/tck/MSSQLBinaryDataTypeEncodeTest.java
vertx-mssql-client/src/test/resources/init.sql

Motivation:
fixes https://github.com/eclipse-vertx/vertx-sql-client/issues/627
Conformance:

Add support for mssql nbcrow & nullable datatypes

---

vertx-mysql-client/src/main/asciidoc/index.adoc
vertx-mysql-client/src/main/java/examples/MySQLClientExamples.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLRowImpl.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/datatype/DataTypeCodec.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/StringDataTypeTest.java

Motivation:
fixes #613 
Conformance:

Add support for enum data type in MySQL

---

vertx-mssql-client/src/main/asciidoc/index.adoc
vertx-mssql-client/src/main/java/examples/MSSQLClientExamples.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLRowImpl.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedQueryCommandCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLDataTypeCodec.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLDataTypeTestBase.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLEnumDataTypeTest.java

Motivation:
fixes https://github.com/eclipse-vertx/vertx-sql-client/issues/614.
Conformance:

Add enum support for mssql

---

pom.xml
vertx-db2-client/src/main/resources/META-INF/MANIFEST.MF
vertx-mssql-client/src/main/resources/META-INF/MANIFEST.MF
vertx-mysql-client/src/main/resources/META-INF/MANIFEST.MF
vertx-pg-client/src/main/resources/META-INF/MANIFEST.MF
vertx-sql-client-templates/src/main/resources/META-INF/MANIFEST.MF
vertx-sql-client/src/main/resources/META-INF/MANIFEST.MF

Signed-off-by: afloarea <adrianfloarea07@yahoo.com>
Motivation:
Add automatic module names as per [#524](https://github.com/vert-x3/issues/issues/524)

Add automatic module names

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryResponse.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/NetSqlca.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2SimpleQueryTest.java

Backport: Fix NPE on query error path and improve error reporting

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2RowImpl.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/ClientTypes.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/SqlCode.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2BinaryDataTypeEncodeTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLBinaryDataTypeEncodeTest.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/BinaryDataTypeEncodeTestBase.java

DB2 support for LocalTime and BigDecimal

---

.travis.yml
vertx-sql-client-templates/src/main/asciidoc/index.adoc
vertx-sql-client-templates/src/main/java/examples/TemplateExamples.java
vertx-sql-client-templates/src/main/java/io/vertx/sqlclient/templates/impl/SqlTemplate.java
vertx-sql-client-templates/src/test/java/io/vertx/sqlclient/templates/DataObjectTypesTest.java
vertx-sql-client-templates/src/test/java/io/vertx/sqlclient/templates/MySQLTest.java
vertx-sql-client-templates/src/test/java/io/vertx/sqlclient/templates/PgClientTest.java
vertx-sql-client-templates/src/test/java/io/vertx/sqlclient/templates/PgTemplateTestBase.java
vertx-sql-client-templates/src/test/java/io/vertx/sqlclient/templates/TemplateBuilderTest.java

Motivation:
Fixes #655
Conformance:

replace SQL template placeholder $ with # instead - fixes #655

---

vertx-sql-client/src/main/java/io/vertx/sqlclient/PreparedStatement.java

PreparedStatement: added createStream variant with empty args

---

vertx-mysql-client/src/main/asciidoc/index.adoc
vertx-mysql-client/src/main/java/examples/MySQLClientExamples.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnectOptions.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnection.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLPool.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionFactory.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionImpl.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionUriParser.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLUnixDomainSocketTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/impl/MySQLConnectionUriParserTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/junit/MySQLRule.java

MySQL Client: Unix Domain Socket support

---

vertx-db2-client/src/main/asciidoc/index.adoc
vertx-db2-client/src/main/java/examples/DB2ClientExamples.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2RowImpl.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2ParamDesc.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryRequest.java
vertx-db2-client/src/test/java/io/vertx/db2client/DB2DataTypeTest.java
vertx-db2-client/src/test/resources/init.sql

Add support for enums in Row/Tuple for DB2
Issue #615

Add support for enums in Row/Tuple for DB2

---

vertx-db2-client/src/main/java/io/vertx/db2client/DB2Exception.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2Decoder.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2PreparedStatement.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/ExtendedQueryCommandBaseCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/NetSqlca.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/SectionManager.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/SqlCode.java

Fix issue when prepared statement caching is enabled for DB2 driver

---

vertx-db2-client/src/main/java/io/vertx/db2client/DB2Exception.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2Decoder.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2PreparedStatement.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/ExtendedQueryCommandBaseCodec.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/NetSqlca.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/SectionManager.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/SqlCode.java

Backport: Fix issue when prepared statement caching is enabled for DB2 driver

---

vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedBatchQueryCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLPreparedStatement.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLPreparedStatementTest.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PreparedStatementTestBase.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SocketConnectionBase.java

Command execution pipeline fixes - close #725 - close #726

---

vertx-pg-client/src/main/java/examples/PgClientExamples.java

Properties example update

---

vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2BinaryDataTypeDecodeTest.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/RowImpl.java
vertx-pg-client/src/test/java/io/vertx/pgclient/RowTest.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/Row.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/Utils.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/BinaryDataTypeDecodeTestBase.java

Row to JSON conversion

---

vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLPoolImpl.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLSocketConnection.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedQueryCommandCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/QueryCommandBaseCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/SQLBatchCommandCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/TdsMessageEncoder.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/EnvChange.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/tck/MSSQLTransactionTest.java
vertx-mssql-client/src/test/resources/init.sql

Transaction support for MSSQL

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2RowDesc.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/ColumnMetaData.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2BinaryDataTypeDecodeTest.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataType.java

DB2 support for ColumnDescriptor

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2RowDesc.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/ColumnMetaData.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2BinaryDataTypeDecodeTest.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ColumnData.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLRowDesc.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/datatype/BitNDataType.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/datatype/FixedLenDataType.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/datatype/FloatNDataType.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/datatype/IntNDataType.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/datatype/MSSQLDataType.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/datatype/NumericDataType.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/datatype/TextWithCollationDataType.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/datatype/TimeNDataType.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/tck/MSSQLBinaryDataTypeDecodeTest.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLRowDesc.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/datatype/DataType.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/protocol/ColumnDefinition.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLBinaryDataTypeDecodeTest.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataType.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgColumnDesc.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgRowDesc.java
vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgBinaryDataTypeDecodeTest.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/SqlResult.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/desc/ColumnDescriptor.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/QueryResultBuilder.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/RowDesc.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlResultBase.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/BinaryDataTypeDecodeTestBase.java

Column descriptor master

---

vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/AuthenticationCommandBaseCodec.java

Motivation:
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Conformance:

Fix MySQL buffer reference leak when allocating for connection attributes

---

vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectionTestBase.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PgTransactionTest.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/TransactionImpl.java

to better handle reentrancy. A few simplification have been made too
fixes #833

Rewrite the internal state transition of the Transaction 

---

vertx-mysql-client/src/main/asciidoc/dataobjects.adoc
vertx-mysql-client/src/main/asciidoc/enums.adoc
vertx-mysql-client/src/main/asciidoc/index.adoc
vertx-mysql-client/src/main/generated/io/vertx/mysqlclient/MySQLConnectOptionsConverter.java
vertx-mysql-client/src/main/java/examples/MySQLClientExamples.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLAuthenticationPlugin.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnectOptions.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionFactory.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLSocketConnection.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ChangeUserCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/InitialHandshakeCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/command/InitialHandshakeCommand.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLAuthenticationPluginTest.java

MySQL default authentication plugin support and cleartext password support

---

vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/TdsMessageDecoder.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLCodec.java

Motivation:
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Conformance:

Fix race for the inflight requests failure reporting

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2ConnectionFactory.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/ClientConfig.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2ConnectionAutoRetryTest.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLConnectionFactory.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/tck/MSSQLConnectionAutoRetryTest.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionFactory.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/ClientConfig.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLConnectionAutoRetryTest.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionFactory.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionImpl.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgPoolImpl.java
vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgConnectionAutoRetryTest.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlConnectionFactoryBase.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/ConnectionAutoRetryTestBase.java

Motivation:
Fixes #805 
Conformance:

Add support for connection retry

---

vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgSocketConnection.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PreparedStatementTestBase.java

Added 42804 to indeterminate statement errors

---

vertx-db2-client/src/main/java/io/vertx/db2client/DB2Connection.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/MSSQLConnection.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnection.java
vertx-pg-client/src/main/java/io/vertx/pgclient/PgConnection.java

This will help working generated APIs like RxJava/Mutiny
Closes https://github.com/vert-x3/vertx-rx/issues/243

Add cast method to connection classes

---

pom.xml

Similar to https://github.com/eclipse-vertx/vertx-sql-client/pull/890

Update testcontainers to 1.15.2 for branch 3.9

---

vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLPoolTest.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PgPoolTest.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PgTestBase.java
vertx-pg-client/src/test/java/io/vertx/pgclient/junit/ContainerPgRule.java
vertx-sql-client/src/main/generated/io/vertx/sqlclient/PoolOptionsConverter.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/PoolOptions.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/PoolBase.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/pool/ConnectionPool.java

Port pool idle timeout changes from 3.9

---

vertx-mssql-client/src/main/asciidoc/index.adoc
vertx-mssql-client/src/main/java/examples/MSSQLClientExamples.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/MSSQLConnectOptions.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/MSSQLConnection.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/MSSQLPool.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLConnectionUriParser.java
vertx-mssql-client/src/test/java/MSSQLConnectOptionsProviderTest.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/impl/MSSQLConnectionUriParserTest.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnection.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLPool.java

Motivation:
Fixes #797
Conformance:

Add support for SQL Server connection URI

---

.github/workflows/ci.yml
pom.xml
vertx-mssql-client/README.adoc
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/junit/MSSQLRule.java

- test latest major versions of MS SQL Server
- simplified jUnit rule
- support external SQL server testing

MS SQL Server testing improvements

---

vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionImpl.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgSocketConnection.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgDecoder.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/TxFailedEvent.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectionTestBase.java
vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgTransactionTest.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlConnectionImpl.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/TransactionImpl.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/command/SimpleQueryCommand.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/TransactionTestBase.java

Transaction should not rollback automatically on a failure

---

vertx-pg-client/src/test/java/io/vertx/pgclient/data/ColumnChecker.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/QueryBase.java

I don't know if I did something wrong or I forgot to check an option but if apply these changes to `3.9` branch I can import the project in Eclipse and Intellij without issues.
In case it helps

Make the project importable in the IDE

---

vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLPoolTest.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PgPoolTest.java

See #935 
Make sure no connection is leaked when using idle-timeout on PoolOptions

Test for connection leaks

---

vertx-mssql-client/src/main/java/io/vertx/mssqlclient/MSSQLException.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLCommandCodec.java

Instead of reporting the last token only, additional tokens are stored in the MS SQL exception.
Also, the exception message will now give all the details instead of the error message only.

MS SQL response can have multiple error tokens

---

vertx-mssql-client/src/main/asciidoc/index.adoc
vertx-mssql-client/src/main/java/examples/MSSQLClientExamples.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLRowImpl.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/BinaryDataType.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedQueryCommandCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLDataTypeCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/QueryCommandBaseCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/VarBinaryDataType.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLFullDataTypeTestBase.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLNullableDataTypeTestBase.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNotNullableDataTypeTest.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNullableDataTypeTest.java
vertx-mssql-client/src/test/resources/init.sql

MSSQL `binary`/`varbinary` data type support using Vert.x `Buffer`.

MSSQL binary/varbinary data type support

---

vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/TdsMessageDecoder.java

Closes #926
Previously, TdsMessageDecoder was a MessageToMessageDecoder which releases the message after decode method.
We never noticed any issues because no test in our test suite leads to a server response that is big enough to be split into different packets.
So the message was always created from newTdsMessageFromSinglePacket and released automatically by Netty.
Now TdsMessageDecoder is a simple ChannelInboundHandlerAdapter and we release the TdsMessage manually after the messages is effectively decoded or the channel handler is removed.

Release TdsMessage after it's been decoded

---

vertx-pg-client/src/test/java/io/vertx/pgclient/PreparedStatementTestBase.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/PreparedStatementImpl.java

Motivation:
Fix for https://github.com/eclipse-vertx/vertx-sql-client/issues/967 (3.9-branch).
Conformance:
Check

Check context when closing cursor (3.9)

---

vertx-sql-client/src/main/java/io/vertx/sqlclient/Tuple.java

javadoc improvements in Tuple.java

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2ConnectionUriParser.java
vertx-db2-client/src/test/java/io/vertx/db2client/DB2ConnectionUriParserTest.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLConnectionUriParser.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/impl/MSSQLConnectionUriParserTest.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionUriParser.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/impl/MySQLConnectionUriParserTest.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionUriParser.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectionUriParserTest.java

Motivation:
Fix bug for 4.1, the same as https://github.com/eclipse-vertx/vertx-sql-client/pull/1019

Fix asterisk parsing in uri parser for 4.1

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryRequest.java
vertx-db2-client/src/test/java/io/vertx/db2client/QueryVariationsTest.java

Ignore comments in Queries

---

vertx-pg-client/README.adoc

Closes #1070 
I've signed the Eclipse CLA

Mention support of INET type in readme

---

vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/Helper.java
vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/OracleQueriesTest.java

Implement conversion for Oracle TIMESTAMPZ

---

vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/PoolImpl.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/pool/SqlConnectionPool.java

Removed unused pooled connection eviction check

---

vertx-oracle-client/README.adoc
vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/junit/OracleRule.java

Two options are added:
- fixed port testing (easier network inspection)
- external database testing (fast turnaround when debugging)

Oracle container testing improvements

---

vertx-oracle-client/src/main/java/io/vertx/oracleclient/OracleConnectOptions.java
vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleConnectionUriParser.java
vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleDatabaseHelper.java
vertx-oracle-client/src/test/java/io/vertx/oracleclient/impl/InvalidOracleConnectionUriParsingTest.java
vertx-oracle-client/src/test/java/io/vertx/oracleclient/impl/ValidOracleConnectionUriParsingTest.java

Support Oracle connection url format using TNSNames alias

---

vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/DataType.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/InitCommandCodec.java

Reduce MSSQL Client ByteBuffer operations where possible

---

vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandBaseCodec.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLPreparedStatementTest.java
vertx-mysql-client/src/test/resources/init.sql

MySQL: close PreparedStatement if needed when server replies with error

---

vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ColumnData.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/DataType.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLCommandCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/RowResultDecoder.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/TypeInfo.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLFullDataTypeTestBase.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNotNullableDataTypeTest.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNullableDataTypeTest.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/tck/MSSQLNullValueEncodeTest.java
vertx-mssql-client/src/test/resources/init.sql

Closes #608 
Commits can be reviewed individually

MSSQL data types enhancements

---

vertx-mssql-client/src/main/java/io/vertx/mssqlclient/MSSQLConnectOptions.java
vertx-oracle-client/src/main/java/io/vertx/oracleclient/OracleConnectOptions.java

Missing fields when copying Oracle or MSSQL connect options

---

vertx-oracle-client/src/main/asciidoc/index.adoc
vertx-oracle-client/src/main/java/examples/OracleClientExamples.java
vertx-oracle-client/src/main/java/io/vertx/oracleclient/data/Blob.java
vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/Helper.java
vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/QueryCommand.java
vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/OracleBinaryDataTypesTest.java
vertx-oracle-client/src/test/resources/tck/import.sql

Implement Oracle binary types encoding and decoding

---

vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/OracleTransactionCommand.java
vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OracleTransactionTest.java

Fixes #1187
Using the executeAsyncOracle method leads to ORA-01000: maximum open cursors exceeded

Make sure no cursors are left open when starting a transaction

---

vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedCursorQueryCommandCodec.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/tck/MSSQLPreparedQueryTestBase.java

NPE when MSSQL query fails to be prepared for streaming

---

vertx-mssql-client/src/main/asciidoc/index.adoc
vertx-mssql-client/src/main/java/examples/MSSQLClientExamples.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/MSSQLConnection.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/MSSQLInfo.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLConnectionImpl.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLSocketConnection.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedCursorQueryCommandCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLCommandCodec.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/MSSQLInfoTest.java

Log MSSQL INFO token content or let users handle it

---

vertx-sql-client/src/main/java/io/vertx/sqlclient/Pool.java

Motivation:
Fix wrong JavaDoc in https://github.com/eclipse-vertx/vertx-sql-client/issues/1206

Fix wrong JavaDoc

---

vertx-mysql-client/src/test/java/io/vertx/mysqlclient/junit/MySQLRule.java

Otherwise, the container fails to start on Fedora (crashes after eating as much memory as possible).

MySQL testing: add limits for nofile to MySQLRule

---

vertx-oracle-client/src/main/asciidoc/index.adoc
vertx-oracle-client/src/main/java/examples/OracleClientExamples.java
vertx-oracle-client/src/main/java/io/vertx/oracleclient/OracleConnectOptions.java

Documentation for Oracle Client Encryption setup

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/ExtendedBatchQueryCommandCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedBatchQueryCommandCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedCursorQueryCommandCodec.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedQueryCommandCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedBatchQueryCommandCodec.java
vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/OraclePreparedBatch.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/ExtendedQueryCommandCodec.java
vertx-sql-client-templates/src/main/java/io/vertx/sqlclient/templates/impl/JsonTuple.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/ArrayTuple.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/ListTuple.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/TupleInternal.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/command/ExtendedQueryCommand.java

Type cache pollution: consistently check for TupleInternal instead of Tuple type compatibility

---

vertx-mysql-client/src/main/asciidoc/cursor_warning.adoc
vertx-sql-client/src/main/asciidoc/cursor.adoc

Document MySQL cursor API limitation with ProxySQL

---

vertx-sql-client/src/main/asciidoc/queries.adoc
vertx-sql-client/src/main/java/io/vertx/sqlclient/Tuple.java

Doc: Row / Tuple indexes start at 0, not at 1

---

vertx-db2-client/src/main/java/io/vertx/db2client/DB2Exception.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2Codec.java
vertx-db2-client/src/test/java/io/vertx/db2client/DB2ErrorMessageTest.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2PreparedQueryCachedTest.java
vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2PreparedQueryTestBase.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/MSSQLException.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/TdsMessageCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLBatchException.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLException.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLCodec.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLConnectionTest.java
vertx-oracle-client/src/main/java/io/vertx/oracleclient/OracleException.java
vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/FailureUtil.java
vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/OracleErrorSimpleTest.java
vertx-pg-client/src/main/java/io/vertx/pgclient/PgException.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgSocketConnection.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgCodec.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PgClientTestBase.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectionTest.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectionTestBase.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PgExceptionTest.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PgTestBase.java
vertx-pg-client/src/test/java/io/vertx/pgclient/PreparedStatementTestBase.java
vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgTransactionTest.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/ClosedChannelException.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/ClosedConnectionException.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/DatabaseException.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/TransactionRollbackException.java

Closes #1274, fixes #1273, closes #1269
Commits can be reviewed individually

Exceptions improvements

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/InitialHandshakeCommandCodec.java

Fixes https://github.com/eclipse-vertx/vertx-sql-client/issues/1287

DB2 client: avoid System.out logging

---

vertx-db2-client/src/main/java/examples/SqlClientExamples.java
vertx-mssql-client/src/main/java/examples/SqlClientExamples.java
vertx-mysql-client/src/main/java/examples/SqlClientExamples.java
vertx-oracle-client/src/main/java/examples/SqlClientExamples.java
vertx-pg-client/src/main/java/examples/SqlClientExamples.java
vertx-sql-client/src/main/asciidoc/pool_config.adoc
vertx-sql-client/src/main/java/examples/SqlClientExamples.java

Dynamic connection provider documentation

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2ParamDesc.java
vertx-db2-client/src/test/java/io/vertx/db2client/DB2DataTypeTest.java
vertx-db2-client/src/test/resources/init.sql
vertx-db2-client/src/test/resources/init.zos.sql

Fix DB2 storage of binary data in char column

---

vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/ClientTypes.java
vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryRequest.java
vertx-db2-client/src/test/java/io/vertx/db2client/DB2QueriesTest.java

Fix DB2 conversions for decimal and long integer values

---

vertx-db2-client/src/test/java/io/vertx/db2client/junit/DB2Resource.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/MSSQLException.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/MSSQLQueriesTest.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/junit/MSSQLRule.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/junit/MySQLRule.java
vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/junit/OracleRule.java
vertx-pg-client/src/main/java/io/vertx/pgclient/PgConnection.java
vertx-pg-client/src/main/java/io/vertx/pgclient/PgException.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionImpl.java
vertx-pg-client/src/test/java/io/vertx/pgclient/junit/ContainerPgRule.java
vertx-sql-client-templates/src/test/java/io/vertx/sqlclient/templates/MySQLTest.java
vertx-sql-client-templates/src/test/java/io/vertx/sqlclient/templates/PgTemplateTestBase.java

Remove deprecated code and replace deprecated code usage 

---

vertx-sql-client-templates/src/main/java/io/vertx/sqlclient/templates/generator/RowMapperGen.java

Autogenerated RowMapper class missing singleton INSTANCE in RxJava/Mutiny

---

vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionFactory.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLTLSTest.java

MySql Client uses SSL settings only for first connection in pool

---

vertx-mssql-client/README.adoc
vertx-mysql-client/README.adoc
vertx-mysql-client/docker/mysql/README.md
vertx-pg-client/README.adoc
vertx-pg-client/docker/postgres/README.md

The docker-compose Python tool is going away.

Docker Compose is now a docker command plugin

---

vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataTypeCodec.java
vertx-pg-client/src/test/java/io/vertx/pgclient/data/MonetaryTypeSimpleCodecTest.java

PgClient Fix money text decoding for negative values

---

vertx-pg-client/src/main/java/io/vertx/pgclient/data/Money.java
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataTypeCodec.java
vertx-pg-client/src/test/java/io/vertx/pgclient/data/MonetaryTypeSimpleCodecTest.java
vertx-pg-client/src/test/java/io/vertx/pgclient/data/MoneyTest.java

Ported from 48420842 and b228e104

PgClient Money bug fixes

---

vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLConnectionFactory.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLSocketConnection.java
vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/InitCommandCodec.java

MSSQL Client routing regression

---

vertx-mysql-client/src/test/java/io/vertx/mysqlclient/ProxySQLBatchInsertExceptionTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/junit/MySQLRule.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/junit/ProxySQLRule.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/ProxySQLPreparedBatchTest.java
vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/ProxySQLPreparedQueryTest.java
vertx-mysql-client/src/test/resources/init.sql

Another attempt to solve #1374

Proxysql setup

---

vertx-mssql-client/src/main/java/io/vertx/mssqlclient/MSSQLException.java
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/MSSQLExceptionTest.java

Set SQL state when there is an exception #1385

---

vertx-pg-client/src/test/java/io/vertx/pgclient/TLSTest.java
vertx-pg-client/src/test/java/io/vertx/pgclient/junit/ContainerPgRule.java
vertx-pg-client/src/test/resources/tls/force_ssl.sh
vertx-pg-client/src/test/resources/tls/pg_hba.conf

Fix SSL falback for SSL MODE ALWAYS

---

vertx-pg-client/README.adoc
vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionFactory.java
vertx-pg-client/src/test/java/io/vertx/pgclient/TLSTest.java
vertx-pg-client/src/test/java/io/vertx/pgclient/junit/ContainerPgRule.java
vertx-pg-client/src/test/resources/tls/force_ssl.sh
vertx-pg-client/src/test/resources/tls/pg_hba.conf

Correct handling of SSL mode always for PostgreSQL

---

vertx-oracle-client/pom.xml

Upgrade to Oracle 23.4.0.24.05

---

.github/workflows/ci-4.x.yml
.github/workflows/ci-5.x.yml
vertx-mssql-client/docker/docker-compose.yml
vertx-mssql-client/docker/initdb.sh
vertx-mssql-client/src/test/java/io/vertx/mssqlclient/junit/MSSQLRule.java

See individual commits for details.

Re-enable MSSQL in CI

---

vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLUnixDomainSocketTest.java
vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/tracing/QueryReporter.java
vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/TracingTestBase.java

See https://github.com/eclipse-vertx/vertx-tracing/issues/69

Use names specified by OpenTelemetry for tags

---

vertx-sql-client/src/main/java/io/vertx/sqlclient/PoolOptions.java

PoolOptions copy constructor doesn't copy all fields

---

vertx-pg-client/src/main/java/io/vertx/pgclient/impl/RowImpl.java
vertx-pg-client/src/test/java/io/vertx/tests/pgclient/data/JavaEnumTest.java

Fix ClassCastException when reading a null arrays of enums 

---

vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/TdsMessageCodec.java
vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLCodec.java

Follows up on on https://github.com/eclipse-vertx/vertx-sql-client/pull/1507

Improve eager command failure in MySQL and SQL Server

---

vertx-pg-client/src/test/java/io/vertx/tests/pgclient/PgBouncerTest.java

This gives us some time to plan a migration. Not sure how much.

Temporarily use bitnamilegacy repository
