- src/main/docs/index.md
- src/main/java/examples/Examples.java
- src/main/java/io/reactiverse/pgclient/PgClient.java
- src/main/java/io/reactiverse/pgclient/PgConnectOptions.java
- src/main/java/io/reactiverse/pgclient/PgConnectOptionsProvider.java
- src/main/java/io/reactiverse/pgclient/PgPoolOptions.java
- src/main/java/io/reactiverse/pgclient/impl/PgConnectionUriParser.java
- src/main/java/io/reactiverse/pgclient/package-info.java
- src/test/java/io/reactiverse/pgclient/PgConnectOptionsProviderTest.java
- src/test/java/io/reactiverse/pgclient/PgConnectionUriParserTest.java
Add feature for connecting with connection URI. Fixes https://github.com/reactiverse/reactive-pg-client/issues/40.
> Enable the client to configure from a connection URI - fixes #40

- src/main/java/io/reactiverse/pgclient/impl/codec/util/MD5Authentication.java
- src/test/java/io/reactiverse/pgclient/impl/codec/util/MD5AuthenticationTest.java
the current build does not run on java >= 10 because:
```
Unhandled exception java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/HexBinaryAdapter
at io.reactiverse.pgclient.impl.codec.util.MD5Authentication.encode(MD5Authentication.java:30)
at io.reactiverse.pgclient.impl.codec.encoder.message.PasswordMessage.<init>(PasswordMessage.java:37)
```
This PR replaces the removed API with a single function that does the hex string encoding and adds a test to verify that the expected result matches what the old API was generating.
> Java>=10 does not contain the xml bind package anymore

- src/main/docs/index.md
- src/main/java/examples/Examples.java
- src/main/java/io/reactiverse/pgclient/impl/pubsub/PgSubscriberImpl.java
- src/main/java/io/reactiverse/pgclient/pubsub/PgSubscriber.java
- src/test/java/io/reactiverse/pgclient/PubSubTest.java
Bug Fix: Using quoted identifiers for channel names would result in notifications not coming back to the channel since the PgNotification would contain a channel name without quotes.  Solved this by making all channel statements use quoted identifiers - this also matches up with use of a standard HashMap (case-sensitive) to match back to channels.
> Use quoted identifiers in LISTEN / UNLISTEN

- README.adoc
- docker/postgres/resources/create-postgres.sql
- docker/postgres_tc/create-postgres.sql
- docs/guide/groovy/index.md
- docs/guide/java/index.md
- docs/guide/js/index.md
- docs/guide/kotlin/index.md
- docs/guide/ruby/index.md
- src/main/java/io/reactiverse/pgclient/impl/codec/DataType.java
- src/main/java/io/reactiverse/pgclient/impl/codec/DataTypeCodec.java
- src/test/java/io/reactiverse/pgclient/DataTypeExtendedEncodingTest.java
- src/test/java/io/reactiverse/pgclient/DataTypeSimpleEncodingTest.java
The current implementation treats unknown as binary, which deviates from other postgres drivers. This issue manifests in the current support for reading enum and enum array values.
This PR:
- Removes the existing enum implementation (the oid was for the text fixture enum, not for enums in general)
- Changes `DataType.UNKNOWN` to be a String instead of a binary type
- Updates encoders and decoders to handle both Strings and array values
- Adds a few tests around array parsing (empties, 1+, etc)
For a point of reference, both the [postres driver](https://github.com/pgjdbc/pgjdbc/blob/9534e9ca0e1840445ad5f4eee75bc1e2ac102dde/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java#L220) and[ Postgres Async](https://github.com/mauricio/postgresql-async/blob/5d0a7e017e90f137a9cb0b0e20947c6bc88 …
> Treat unknown datatypes as text instead of binary

- src/test/java/io/reactiverse/pgclient/DataTypeWideningTest.java
That gives the error message `Values [5] cannot be coerced to [Long]` which is
at least missleading.
Demonstrating #179
> A simple test for numeric typing

- docker/postgres_tc/Dockerfile
- docker/postgres_tc/README.md
Hi @vietj.  I was following the instructions for setting up a system with a network latency (in the postgres_tc folder), and came across two minor issues, so here's a suggested PR with a couple of changes you might want to consider:
- The instructions referred to a container called `julien-test`, but the previous step created it with a name of `test-postgres_tc` (at least as far as I understand). So I guess they should both be using the same name?
- The supplied Dockerfile didn't work for me, and I tracked it down to a recommendation from Docker that when using `apt-get` you should combine `update` and `install` into the same `RUN` statement. Details in this SO answer: https://stackoverflow.com/a/42981752/10326373
Hope this is of some use.
> Two minor changes in docker file and instructions for using tc to add latency

- README.adoc
- docker/postgres/Dockerfile
- docker/postgres/README.md
- docker/postgres/docker-compose.yml
- pom.xml
- src/main/java/io/reactiverse/pgclient/impl/codec/decoder/InitiateSslHandler.java
- src/test/java/io/reactiverse/pgclient/PgClientTestBase.java
- src/test/java/io/reactiverse/pgclient/PgTestBase.java
- src/test/java/io/reactiverse/pgclient/TLSTest.java
- src/test/java/io/reactiverse/pgclient/UnixDomainSocketTest.java
This PR is for #206 but with some addtional changes:
1. Add support for unit testing with non SSL embedded Postgres server and configurable for this.
2. Make all tests by default use non SSL Postgres server if necessary.
3.Expose connection failure to users directly when connecting to a non-SSL Postgres server with SSL option on.
Failure handling is more straightforward when connecting to Non SSL Postgres server like this:
```
PgConnectOptions options = new PgConnectOptions()
.setSsl(true)
.setTrustAll(true)
.setHost("localhost")
.setPort(5432)
.setUser("postgres")
.setPassword("password")
.setDatabase("postgres");
PgClient.connect(vertx, options,
ar -> {
if (ar.succeeded()) {
// not called here
} else {
// Expected Behavior
// directly report to users "Postgres Server does not handle SSL …
```
> Better SSL failure handling when connecting to non SSL Postgres server - fixes #206

- pom.xml
- src/main/asciidoc/dataobjects.adoc
- src/main/docs/index.md
- src/main/java/examples/Examples.java
- src/main/java/io/reactiverse/pgclient/PgClient.java
- src/main/java/io/reactiverse/pgclient/PgConnectOptions.java
- src/main/java/io/reactiverse/pgclient/PgPoolOptions.java
- src/main/java/io/reactiverse/pgclient/SslMode.java
- src/main/java/io/reactiverse/pgclient/impl/PgConnectionFactory.java
- src/main/java/io/reactiverse/pgclient/impl/PgConnectionUriParser.java
- src/main/java/io/reactiverse/pgclient/impl/PgPoolImpl.java
- src/main/java/io/reactiverse/pgclient/impl/SocketConnection.java
- src/main/java/io/reactiverse/pgclient/impl/codec/decoder/InitiateSslHandler.java
- src/main/kotlin/io/reactiverse/kotlin/pgclient/PgConnectOptions.kt
- src/main/kotlin/io/reactiverse/kotlin/pgclient/PgPoolOptions.kt
- src/test/java/io/reactiverse/pgclient/PgClientTestBase.java
- src/test/java/io/reactiverse/pgclient/PgConnectOptionsProviderTest.java
- src/test/java/io/reactiverse/pgclient/PgConnectionUriParserTest.java
- src/test/java/io/reactiverse/pgclient/PgTestBase.java
- src/test/java/io/reactiverse/pgclient/TLSTest.java
- src/test/java/io/reactiverse/pgclient/UnixDomainSocketTest.java
- src/test/java/io/reactiverse/pgclient/it/EnvTest.java
This PR is to fix #207.
Changes:
- add support for **sslmode**
- **ssl** parameter is now deprecated and **sslmode** should be used instead.
Client is in `DISABLE` mode by default, `setSsl(true)` is equivalent to `setSslMode(REQUIRE)` and `setSsl(false)` is equivalent to `setSslMode(DISABLE)` so that we can avoid break changes.
- refactor PgConnectionFactory and SocketConnection class
> Add support for sslmode - fixes #207

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ChangeUserCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/CloseConnectionCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/CloseStatementCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/CommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/DebugCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/InitCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/InitDbCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLDecoder.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/PingCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/PrepareStatementCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/QueryCommandBaseCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ResetConnectionCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ResetStatementCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/SetOptionCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/StatisticsCommandCodec.java
The param `MySQLEncoder` of MySQL command codec method `decodePayload` is unnecessary because it's actually a field in the codec, thus we can simply drop them.
> MySQL cleanup

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/DataTypeCodec.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/DateTimeBinaryCodecTest.java
- vertx-mysql-client/src/test/resources/init.sql
the encoding fractional seconds value should be encoded as `int4` type instead of `int1` type - fixes #348.
> Fix the incorrect MySQL DATETIME/TIMESTAMP datatype encoding implementation

- vertx-pg-client/README.adoc
- vertx-pg-client/src/main/asciidoc/index.adoc
- vertx-pg-client/src/main/java/examples/PgClientExamples.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataType.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataTypeCodec.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/TsTypesExtendedCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/TsTypesSimpleCodecTest.java
fix #371 
Hi, 
Here is a PR to support text search types. 
I have handled tsquery and tsvector as text (not with a dedicated type) because usually this types are calculated from text using functions and I don't think a dedicated type would be useful. 
I have written some tests and I'm not sure I have the same coverage of case that the tests for other types so if you see missing case tell me! 
In the DataType enum I have set `supportsBinary` to `false` because it doesn't work when the value is `true` (word are truncated and I don't know why). I don't find informations on why types are eligible to binary/text encoding.
> support for ts types

- vertx-mysql-client/src/main/java/examples/SqlClientExamples.java
- vertx-pg-client/src/main/asciidoc/index.adoc
- vertx-pg-client/src/main/java/examples/SqlClientExamples.java
- vertx-sql-client/src/main/asciidoc/cursor.adoc
- vertx-sql-client/src/main/asciidoc/queries.adoc
- vertx-sql-client/src/main/java/examples/SqlClientExamples.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/Row.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/SqlResult.java
* https://github.com/eclipse-vertx/vertx-sql-client/commit/bd953d023d0f5897b67384693254fc8d8e97941f - fixes #390
* https://github.com/eclipse-vertx/vertx-sql-client/commit/6b085ee3508a76921c21ed24cc460e009c26dde1 - fixes missing examples for batching queries in MySQL
* https://github.com/eclipse-vertx/vertx-sql-client/commit/dd6b0eb33572e4ea589637d1cd6d41206117e2a8 - move the Postgres specific docs out of the `sqlclient`
* https://github.com/eclipse-vertx/vertx-sql-client/commit/05e2aa08fa9135aabedeb1e26de282855a8f2e2e - fixes #388
> Documentation improvements

- vertx-mysql-client/README.adoc
- vertx-mysql-client/src/main/asciidoc/index.adoc
- vertx-mysql-client/src/main/java/examples/MySQLClientExamples.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLEncoder.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLQueryTest.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLStoredProgramsTest.java
We have already supported the stored procedures via the queries and we do not need to introduce something like `CallableStatement`.
Add tests and documentation for stored procedures - fixes #402
> MySQL stored procedures support

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/DataTypeCodec.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/MySQLDataTypeTestBase.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/StringDataTypeTest.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataTypeCodec.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/BinaryDataTypesExtendedCodecTest.java
@vietj Did not found a prettier solution for copying the `ByteBuf` to a heap `Buffer` without calling low level parts e.g. `PartialPooledByteBufAllocator`.
> Fixed copy of direct buffers causes leak.

- .travis.yml
- pom.xml
- vertx-mysql-client/pom.xml
- vertx-pg-client/pom.xml
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgProtocolConstants.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PgTestBase.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/TLSTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/UnixDomainSocketTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/junit/ContainerPgRule.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/junit/PgRule.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgBinaryDataTypeDecodeTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgBinaryDataTypeEncodeTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgCollectorTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgConnectionTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgPreparedBatchTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgPreparedQueryCachedTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgPreparedQueryTestBase.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgSimpleQueryPooledTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgSimpleQueryTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgTextDataTypeDecodeTest.java
The unix socket test has **not** been migrated (4 tests in
UnixDomainSocketTest).
As it's not compatible with my platform see #385
The original PGRule has been modified to automatically ignore unix
socket tests on PG versions unsupported by yandex EmbeddedPostgres.
This is done with ExternalResource#apply to prevent the db from throwing
error at startup (vs junit Assume).
A new travis job for PG 11 has been added.
> Migrate Postgresql tests on Testcontainers

- vertx-mysql-client/src/main/java/examples/MySQLClientExamples.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLClient.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedBatchQueryCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandBaseCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/QueryCommandBaseCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/SimpleQueryCommandCodec.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLQueryTest.java
Fix #471.
This is a backport to `3.8` of #472
> MySQL lastInsertId should be represented as Long type instead of Integer

- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/TransactionImpl.java
Signed-off-by: Dimitris Zenios <dimitris.zenios@gmail.com>
I am not sure if its better to add both commit and rollback methods (that accept handler) as default methods on the interface
> Removed duplicated code

- vertx-mysql-client/src/main/asciidoc/index.adoc
- vertx-mysql-client/src/main/java/examples/MySQLClientExamples.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ColumnDefinition.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/DataType.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/DataTypeCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedBatchQueryCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandBaseCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLParamDesc.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/Packets.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/RowResultDecoder.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLPreparedStatementTest.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/DateTimeBinaryCodecTest.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/MySQLDataTypeTestBase.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/NumericDataTypeTest.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLPreparedQueryCachedTest.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLPreparedQueryTest.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLPreparedQueryTestBase.java
Motivation:
The MySQL server will not return the parameter metadata in the COM_STMT_PREPARE response, therefore client knows nothing about the parameter metadata of prepared statement.
Changes:
1. MySQL prepared statement bind values data types are inferenced from the values provided by the user and could be any type now.
2. Enable the usage of the sendtype flag, if a statement is executed without changing the bind types, it does not have to send the parameter metadata to the server again when performing a COM_STMT_EXECUTE command, this will only work for the preparedQuery but not for cursor and batch.
3. For prepared batch statement it will still behave like before, the data type will be inferenced by the value and the parameter metadata will always be sent to the server.
> MySQL preparedStatement rework

- vertx-mysql-client/pom.xml
- vertx-pg-client/README.adoc
- vertx-pg-client/docker/postgres/resources/create-postgres.sql
- vertx-pg-client/pom.xml
- vertx-pg-client/src/main/asciidoc/index.adoc
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/InitCommandCodec.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgCommandCodec.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgDecoder.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgEncoder.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/ScramClientFinalMessage.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/ScramClientInitialMessage.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/util/ScramAuthentication.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PgScramConnectionTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/junit/ContainerPgRule.java
support SASL SCRAM-SHA-256 as an authentication mechanism.
SCRAM-SHA-256-PLUS (added in Postgresql 11) is **not** supported.
The scram part is provided by _om.ongres.scram:client_ (BSD 2-Clause "Simplified" License), this is a new dependency.
This library also provides the scram support in pgjdbc.
Please review carefully, I'm not intimate with the vertx-pg-client source code.
> add sasl SCRAM-SHA-256 authentication mechanism

- vertx-db2-client/src/main/java/io/vertx/db2client/DB2ConnectOptions.java
- vertx-db2-client/src/test/java/io/vertx/db2client/DB2SimpleQueryUriTest.java
Signed-off-by: Mark Swatosh <mark.swatosh@gmail.com>
Motivation:
Enabling the URI parsing code for the DB2 driver, and adding a basic test.
Conformance:
> Enabling uri string and tests

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2SocketConnection.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/CloseConnectionCommandCodec.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/InitialHandshakeCommandCodec.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2ConnectionTest.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SocketConnectionBase.java
Fixing the close path for the db2 driver. 
Fixing an issue with the invalid database names, when the db2 server stops responding properly.
All the connection tests for the TCK are passing now.
Related to #490
Signed-off-by: Mark Swatosh <mark.swatosh@gmail.com>
> Fixing invalid database path and close connection handling

- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLTLSTest.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/junit/MySQLRule.java
Enable TLS protocol v1.2 for testing TLS with MySQL server of 5.7+ versions - fixes #532
> MySQL TLS testing fix

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnection.java
Motivation:
`MySQLConnection#preparedBatch` are not overrided in the `MySQLConnection` interface and it should be overrided so it can return `MySQLConnection` instead of `SqlConnection`.
> Add missing override methods for MySQLConnection interface

- .travis.yml
Travis only runs 4 jobs in parallel at max, which currently means all of the MySQL tests were running initially and we need to wait a few minutes for them to be done until we start getting results for the other DBs.
This PR just reorders the jobs so that those 4 initial jobs that get kicked off are one of each DB type.
> Reorder TravisCI jobs so all DBs run sooner (i.e. fail faster)

- vertx-db2-client/.gitignore
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/CommandCodec.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2Decoder.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/ColumnMetaData.java
- vertx-db2-client/src/test/java/io/vertx/db2client/DB2TestBase.java
- vertx-db2-client/src/test/java/io/vertx/db2client/QueryVariationsTest.java
- vertx-db2-client/src/test/java/io/vertx/db2client/TableJoinTest.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/ListTuple.java
This PR mainly just adds tests for various queries which happened to work already.
Also, it exposed an issue where the DB2Codec was reading ahead slightly in order to check a "sequence ID" which was a holdover from the copied MySQL code. The sequence ID only applies to MySQL codec and therefore can be removed from DB2
Fixes #551
> Add tests for table joins and subqueries

- vertx-pg-client/src/main/java/io/vertx/pgclient/PgConnectOptions.java
Motivation:
fixes #528 
Conformance:
> Remove redundant Postgres property intervalStyle

- vertx-pg-client/pom.xml
Signed-off-by: Paulo Lopes <pmlopes@gmail.com>
Motivation:
The current scram optional dependency is a beta release. Since its release a official production release has beed added and more after that that have been properly tested on the jdbc postgres driver.
> Avoid using a beta release and use the latest stable

- vertx-db2-client/src/main/asciidoc/dataobjects.adoc
- vertx-db2-client/src/main/generated/io/vertx/db2client/DB2ConnectOptionsConverter.java
- vertx-db2-client/src/main/java/io/vertx/db2client/DB2ConnectOptions.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2ConnectionFactory.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2SocketConnection.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/CloseConnectionCommandCodec.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/CloseCursorCommandCodec.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2Decoder.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2Encoder.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/ExtendedBatchQueryCommandCodec.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/ExtendedQueryCommandBaseCodec.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/ExtendedQueryCommandCodec.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/InitialHandshakeCommandCodec.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/PingCommandCodec.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/PrepareStatementCodec.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/QueryCommandBaseCodec.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/SimpleQueryCommandCodec.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/ConnectionMetaData.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/Cursor.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAConnectRequest.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAConnectResponse.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryRequest.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryResponse.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDARequest.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAResponse.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/Typdef.java
Changes in this PR:
- Added pipelining configurability. Currently it defaults to 1 (pipelining is disabled) which is no behavior change. Doing experimentation locally with raising this but it's still very unstable.
- Renamed DatabaseMetaData to ConnectionMetaData and moved from the SocketConnection to DB2Encoder level
- Added handling for OPNQRYFLM and SYNTAXRM code points, which only occur on error paths (Supports #490)
> Initial experimentation with DB2 pipelining

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/AuthenticationCommandBaseCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ChangeUserCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/CloseConnectionCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/CloseStatementCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/CommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/DebugCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedBatchQueryCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandBaseCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/InitDbCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/InitialHandshakeCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLDecoder.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLEncoder.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/PingCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/PrepareStatementCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/QueryCommandBaseCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ResetConnectionCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ResetStatementCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/SetOptionCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/SimpleQueryCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/StatisticsCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/protocol/CapabilitiesFlag.java
Motivation:
* disable CLIENT_SESSION_TRACK flag as it's not used for now, and simplify the OkPacket payload handling
* move sequenceId from `CommandCodec` to `MySQLEncoder` since it's a session state and does not need to be allocated for every command
* clean up channel inbound packet read logic
Conformance:
> MySQL codebase clean up

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2Decoder.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAConnectResponse.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/SqlCode.java
- vertx-db2-client/src/test/java/io/vertx/db2client/DB2ErrorMessageTest.java
Change the default messaging behavior for handling trivial error paths like invalid credentials.
> Implement proper handling and messages for connection error paths

- vertx-db2-client/src/main/java/examples/SqlClientExamples.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2PreparedStatement.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/PrepareStatementCodec.java
- vertx-mssql-client/src/main/java/examples/SqlClientExamples.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLPreparedStatement.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/PrepareStatementCodec.java
- vertx-mysql-client/src/main/java/examples/SqlClientExamples.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLPreparedStatement.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/PrepareStatementCodec.java
- vertx-pg-client/src/main/java/examples/SqlClientExamples.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/CloseStatementCommandCodec.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgEncoder.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgPreparedStatement.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PrepareStatementCommandCodec.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PreparedStatementTestBase.java
- vertx-sql-client/src/main/asciidoc/connections.adoc
- vertx-sql-client/src/main/asciidoc/queries.adoc
- vertx-sql-client/src/main/java/examples/SqlClientExamples.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/PreparedStatement.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SocketConnectionBase.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlClientBase.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlConnectionBase.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/command/PrepareStatementCommand.java
Motivation:
fixes #577 
Conformance:
> Prepared statement created by SqlConnection#prepare should not be cached 

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAConnectResponse.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAConstants.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryResponse.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2BinaryDataTypeDecodeTest.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2BinaryDataTypeEncodeTest.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2CollectorTest.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2ConnectionTest.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2PreparedBatchTest.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2PreparedQueryCachedTest.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2PreparedQueryTestBase.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2SimpleQueryPooledTest.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2SimpleQueryTest.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2TextDataTypeDecodeTest.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2TransactionTest.java
DB2 servers use a 3-char PRDID (product ID) string to identify which type of client they are interacting with, so that extra DB-side features can be enabled/disabled based on what certain clients support.
This PR converts to a new PRDID "JNT" (short for Java Netty client) and also makes a few minor changes in the way DRDA protocol is processed with that PRDID.
> Use unique PRDID of JNT

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/InitialHandshakeCommandCodec.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DB2Package.java
Currently for every new connection that DB2 makes, there are 2 round-trips happening with the DB:
```
<<< EXCSAT | ACCSEC 
>>> EXCSATRD | ACCSECRD
<<< SECCHK | ACCRDB
>>> SECCHKRM | ACCRDBRM
```
The reason for this is that in the initial exchange (`EXCSAT | ACCSEC`) there is supposed to be some sort of DB protocol version negotiation, but since we currently only support one protocol version, we can inline all of this to one round-trip like so:
```
<<< EXCSAT | ACCSEC | SECCHK | ACCRDB
>>> EXCSATRD | ACCSECRD | SECCHKRM | ACCRDBRM
```
> Reduce initial handshake from 2 server round-trips to 1 round-trip

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLRowImpl.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLDataTypeTestBase.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLEnumDataTypeTest.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLFullDataTypeTestBase.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLNullableDataTypeTestBase.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNotNullableDataTypeTest.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNullableDataTypeTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/BinaryDataTypesExtendedCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/BooleanTypeExtendedCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/CharacterTypesExtendedCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/CustomTypesExtendedCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/CustomTypesSimpleCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/DataTypeTestBase.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/DateTimeTypesExtendedCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/DateTimeTypesSimpleCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/EnumeratedTypesExtendedCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/EnumeratedTypesSimpleCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/GeometricTypesExtendedCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/JsonTypesExtendedCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/JsonTypesSimpleCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/NullSimpleCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/NumericTypesExtendedCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/NumericTypesSimpleCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/SimpleQueryDataTypeCodecTestBase.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/TsTypesExtendedCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/TsTypesSimpleCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/UUIDTypeExtendedCodecTest.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/ColumnChecker.java
Motivation:
Move `ColumnChecker` from postgres client to test base, and use it for MSSQL datatype testing.
Conformance:
> Enable column checker for MSSQL datatype testing

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryResponse.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/NetSqlca.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2SimpleQueryTest.java
Fixes https://github.com/hibernate/hibernate-reactive/issues/132
Also improves error messages to include data about what parts of SQL were causing issues. For example:
Before: `The database provided was not found`
After: `The database 'BOGUS_DB' provided was not found`
> Fix NPE on query error path and improve error reporting

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2RowImpl.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/ClientTypes.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/SqlCode.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2BinaryDataTypeEncodeTest.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLBinaryDataTypeEncodeTest.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/BinaryDataTypeEncodeTestBase.java
Also enhances the TCK tests a bit to ensure we are testing the `Row.getXXX()` code paths. Previously we were only testing `Row.getValue(int)` and `Row.getValue(String)`
> DB2 support for LocalTime and BigDecimal

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2ConnectionImpl.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2PoolImpl.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLConnectionImpl.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLPoolImpl.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionImpl.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLPoolImpl.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionImpl.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgPoolImpl.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/TracingTest.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/CursorImpl.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/PoolBase.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/PreparedStatementImpl.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/QueryBase.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/QueryExecutor.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/QueryResultBuilder.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlClientBase.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlConnectionBase.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlConnectionImpl.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlResultBuilder.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlResultHandler.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/tracing/QueryRequest.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/tracing/QueryTracer.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/tracing/SqlTracer.java
Vert.x 4 supports tracing.
Fixes https://github.com/eclipse-vertx/vertx-sql-client/issues/653
> Tracing support

- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2TracingTest.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/tck/MSSQLTracingTest.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLTracingTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/TracingTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgTracingTest.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/TracingTestBase.java
Motivation:
* Fix racy tests because the query result completion handle might be completed before the trace request/response is handled.
* Move Tracing tests to TCK in SQL client base now and get all modules tested with them.
Conformance:
> Rework Tracing tests

- vertx-pg-client/src/test/java/io/vertx/pgclient/PgPoolTestBase.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/pool/ConnectionPool.java
Motivation:
available pooled connection deque in `ConnectionPool` might poll a null value which might cause the client hangs.
Conformance:
> Make recycling pooled connection events emitted on the eventloop context associated with connection pool

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLDatabaseMetadata.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/InitialHandshakeCommandCodec.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLServerVersionParserTest.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLConnectionTest.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/spi/DatabaseMetadata.java
Motivation:
Rework MySQL client server version parsing so that it can parse different types of database version string syntax and support the database metadata SPI as well.
Conformance:
> Rework MySQL client server version parsing

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2RowImpl.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/ClientTypes.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryRequest.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/NetSqlca.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/SqlCode.java
- vertx-db2-client/src/test/java/io/vertx/db2client/DB2DataTypeTest.java
- vertx-db2-client/src/test/java/io/vertx/db2client/DB2ErrorMessageTest.java
- vertx-db2-client/src/test/resources/init.sql
- vertx-sql-client/src/main/java/io/vertx/sqlclient/Tuple.java
Since DB2 does not have an actual UUID column, we will just treat UUIDs as strings
This fixes a limitation that @gavinking ran into with hibernate reactive
> DB2 support for UUID

- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/tracing/QueryTracer.java
Signed-off-by: Paulo Lopes <pmlopes@gmail.com>
Motivation:
Other implementations (JDBC for example) will not use a SqlConnectionOptions as the connection is managed by the driver, so in order to keep the tracer to work for other kinds of drivers, the constructor should just take the required arguments instead.
> Decouple the tracer from SqlConnectionOptions

- vertx-db2-client/src/main/asciidoc/index.adoc
- vertx-db2-client/src/main/java/examples/DB2ClientExamples.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2RowImpl.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2ParamDesc.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryRequest.java
- vertx-db2-client/src/test/java/io/vertx/db2client/DB2DataTypeTest.java
- vertx-db2-client/src/test/resources/init.sql
Backport support for enums in Row/Tuple for DB2 to Vertx 3.9
Issue #615
> Backport support for enums in Row/Tuple for DB2 to 3.9

- vertx-pg-client/src/test/java/io/vertx/pgclient/PgPoolTest.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/PoolBase.java
> Pool implementation for one-shot queries does not use all available resources

- vertx-pg-client/src/test/java/io/vertx/pgclient/PgPoolTest.java
On my local machine I often get this failure:
`PgPoolTest.lambda$null$19:184 Not equals : 11 != 9`
Solution: Increase the delay of the count query.
> Increase delay in PgPoolTest.testUseAvailableResources

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/datatype/DataTypeCodec.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/JsonBinaryCodecTest.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/JsonTextCodecTest.java
> Decoding MySQL JSON data type should only use UTF-8 charset

- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataTypeCodec.java
If the Java default Locale is set to Locale.GERMAN or Locale.JAPANESE
DataTypeCodec fails with
`DateTimeParseException: Text '4714-11-24 00:00:00 BC' could not be parsed`.
The German and Japanese strings are
`4714-11-24 00:00:00 v. Chr.`
`4714-11-24 00:00:00 紀元前`
Use Locale.ROOT for parsing to ignore any default Locale.
> DataTypeCodec with Locale cannot parse '4714-11-24 00:00:00 BC'

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/AuthenticationCommandBaseCodec.java
Motivation:
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Conformance:
> Fix MySQL buffer reference leak when allocating for connection attributes

- vertx-sql-client/src/main/java/io/vertx/sqlclient/Transaction.java
Fix method summary of Transaction.completion javadoc
* "and" is missing in the method summary of Transaction.completion on
https://vertx-web-site.github.io/docs/apidocs/io/vertx/sqlclient/Transaction.html
* "rollbacks" should be "rolls back".
Old text:
"Return the transaction completion Future that succeeds when the transaction
commits fails with TransactionRollbackException when the transaction
**rollbacks**"
New text:
"Return the transaction completion Future that succeeds when the transaction
commits **and** fails with TransactionRollbackException when the transaction
**rolls back**"
> Fix method summary of Transaction.completion javadoc

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/SimpleQueryCommandCodec.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLQueryTest.java
Motivation:
Currently when the client executes loading an empty file request, it will incorrectly send duplicated empty packets to the server which leads to corrupting the session.
fixes #827
> Fix the incorrect execution flow for handling MySQL infile request empty file

- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgCodec.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectionTest.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SocketConnectionBase.java
Postgres fix for https://github.com/eclipse-vertx/vertx-sql-client/issues/837.
> add a test for verifying postgres inflight commands being reported failure when connection gets closed

- vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectionTestBase.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlConnectionImpl.java
Motivation:
fix #847 
Conformance:
> The close handler should be called when the sql connection is closed from a different context

- vertx-pg-client/src/test/java/io/vertx/pgclient/data/DateTimeTypesSimpleCodecTest.java
If Java time zone is +1200 and connection time zone is +0000
then Java will be one day ahead the database connection date
when the test runs before noon.
> Use UTC timezone when testing LocalDate

- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2ConnectionAutoRetryTest.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/tck/MSSQLConnectionAutoRetryTest.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLConnectionAutoRetryTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgConnectionAutoRetryTest.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/ConnectionAutoRetryTestBase.java
PgConnectionAutoRetryTest connects to the proxy using the
hostname returned by ContainerPgRule.
This differs from `localhost` in some CI environments, see #854 and
https://www.testcontainers.org/features/networking/#getting-the-container-host
This needs to be changed to `localhost`, the proxy hostname,
to make the tests succeed.
ConnectionAutoRetryTestBase connects to the database using
`localhost` as hostname. The hostname of the database differs
from `localhost` in some CI environments.
Use the hostname returned by ContainerPgRule to make the tests succeed.
Fixes #854
> Fix the incorrect hostname of proxy server in connection auto retry testsuite

- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgCodec.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgEncoder.java
Signed-off-by: Emad Alblueshi <emad.albloushi@gmail.com>
Motivation:
Removes unused decodor from 'PgEncoder' and 'PgCodec'
Conformance:
> Removes unused decodor from 'PgEncoder' and 'PgCodec'

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLRowImpl.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedQueryCommandCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLDataTypeCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/QueryCommandBaseCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/datatype/DateTime2NDataType.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLDataTypeTestBase.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLFullDataTypeTestBase.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLNullableDataTypeTestBase.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNotNullableDataTypeTest.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNullableDataTypeTest.java
- vertx-mssql-client/src/test/resources/init.sql
- vertx-sql-client/src/test/java/io/vertx/sqlclient/ColumnChecker.java
> Support for datetime2 data type

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/datatype/DataTypeCodec.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/DateTimeCodecTest.java
Signed-off-by: chno9133 <pawel.adamik@agilecode.pl>
Motivation:
Fixed errors while decoding empty date. Both in binary and text protocol. 
Tests are provided.
> Fixed error on empty DATE handling in binary and text protocol

- vertx-pg-client/src/main/asciidoc/index.adoc
This was using MD syntax rather than AsciiDoc.
I'm also having some doubts about the "Getting Started" example. When running this in a simple main method, the program is finished before the (asynchronous) result handler is invoked. Shouldn't there be a countdown latch or other means in place to make sure the result is received before the program terminates?
> Fixing incorrect link syntax

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/CommandCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedQueryCommandCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/InitCommandCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/PreLoginCommandCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/SQLBatchCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/CommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/SimpleQueryCommandCodec.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/InitiateSslHandler.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgEncoder.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SocketConnectionBase.java
Motivation:
use void promise instance to save memory allocation.
Conformance:
> Netty channel write and flush should try to use void channel promise

- vertx-pg-client/src/test/java/io/vertx/pgclient/PgPoolTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PgPoolTestBase.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PgTestBase.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/junit/ContainerPgRule.java
- vertx-sql-client/src/main/asciidoc/dataobjects.adoc
- vertx-sql-client/src/main/java/io/vertx/sqlclient/PoolOptions.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/ConnectionPool.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/PoolBase.java
Original Ref: #881 
* pool idle configuration it's handler by 'PoolOptions'.
* By default idle is not enable (connections doesn't expire)
* Connections expiration time is managed by  `ConnectionPool -> PooledConnection` inner class through Vertx timers.
> Vertx pool Idle timeout

- pom.xml
- vertx-mssql-client/pom.xml
Any particular reason for using an older version of Testcontainers?
I've sent a separate PR for 3.9: https://github.com/eclipse-vertx/vertx-sql-client/pull/891
This PR also fixes some of the errors in CI (not all of them because there are still some timouts)
> Upgrade Testcontainers to 1.15.2

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLDatabaseMetadata.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLServerVersionParserTest.java
Motivation:
Fix "WARNING: Incorrect parsing server version tokens" problem with facebook branch of mysql build from sources.
> Fix MySQL server version parser for whitespaces

- vertx-pg-client/src/main/asciidoc/index.adoc
Signed-off-by: chengen.zhao@mail.mcgill.ca <chengen.zhao@mail.mcgill.ca>
previous pr: https://github.com/eclipse-vertx/vertx-sql-client/pull/904
Motivation:
Hi during the translation to Chinese, we found some looks like format problems
it should be like these:
but actually it looks like
I think this could because of capitalization issues e.g. NOTE: rather than Note:
> During the translation, we found some format problems

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLDataTypeCodec.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLDateTime2DataTypeTest.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLTimeDataTypeTest.java
- vertx-mssql-client/src/test/resources/init.sql
Fixes #752
Previously, TIME(6) and DATETIME2(6) were working but others may not (e.g. DATETIME2(7)).
With this change, all scales from 0 to 7 are supported.
MS SQL servers stores time values in hundred of nanoseconds, with the scale being the number of decimals after the second.
> MS SQL: Fix time and datetime2 scale handling

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedQueryCommandCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLDataTypeCodec.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLFullDataTypeTestBase.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNotNullableDataTypeTest.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNullableDataTypeTest.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/tck/MSSQLBinaryDataTypeEncodeTest.java
The client was able to decode row values but not to encode query parameters.
This commit implements encoding and simplifies decoding.
> Fixes for numeric/decimal support

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedQueryCommandCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/SQLBatchCommandCodec.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/MSSQLQueriesTest.java
Fixes #948
The codecs were not able to handle ORDER_BY tokens
> MSSQL queries failure when ORDER BY clause is present

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLDataTypeCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/QueryCommandBaseCodec.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/MSSQLQueriesTest.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/junit/MSSQLRule.java
Fixes #949
This is important because the current_timestamp function returns a datetime value.
> MSSQL Client support for datetime columns

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLDataTypeCodec.java
This to avoid truncations if value doesn't fit
> MS SQL Always use max precision/scale when inferring column type

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/InitCommandCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/protocol/client/login/LoginPacket.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/MSSQLQueriesTest.java
Fixes #963
In particular, ODBC_ON implies ANSI_DEFAULTS which activates the following ISO behaviors:
- ANSI_NULLS
- CURSOR_CLOSE_ON_COMMIT
- ANSI_NULL_DFLT_ON
- IMPLICIT_TRANSACTIONS
- ANSI_PADDING
- QUOTED_IDENTIFIER
- ANSI_WARNINGS
> MS SQL Connection Options: same as JDBC

- vertx-mssql-client/src/main/asciidoc/index.adoc
- vertx-mssql-client/src/main/java/examples/MSSQLClientExamples.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/MSSQLQueriesTest.java
- vertx-mssql-client/src/test/resources/init.sql
> MSSQL: Document identity column retrieval

- .gitignore
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/CodePoint.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryResponse.java
- vertx-db2-client/src/test/java/io/vertx/db2client/QueryVariationsTest.java
> 837 fix for 3.9

- .gitignore
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/CodePoint.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryResponse.java
- vertx-db2-client/src/test/java/io/vertx/db2client/QueryVariationsTest.java
fixes #887 
Adds the QRYBLKFCT (0x215f) codepoint, which was causing an exception when 'fetch first n rows only' was used.
> Adding and Handling QRYBLKFCT codepoint

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedQueryCommandCodec.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNotNullableDataTypeTest.java
- vertx-mssql-client/src/test/resources/init.sql
Fixes #977
LocalTime, LocalDateTime and OffsetDateTime have nanosecond precision.
Also, the maximum scale in MSSQL is 7 (hundreds of nanos).
So when encoding time-related values, we will always send a value with maximum scale.
The server will do round/truncate as necessary.
> MSSQL: Fix datetime2 encoding

- vertx-mssql-client/README.adoc
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/junit/MSSQLRule.java
- vertx-pg-client/README.adoc
- vertx-pg-client/src/test/java/io/vertx/pgclient/junit/ContainerPgRule.java
This simplifies debugging with tools like wireshark.
> Allow to configure database container with a fixed port

- vertx-pg-client/src/main/java/io/vertx/pgclient/data/Line.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PreparedStatementTestBase.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/GeometricTypesSimpleCodecTest.java
see #991 
> Seems there is nothing new in pg 13 to break vertx-pg-client. Only a validation for line type added. Also pg13 refuses to start with 1024 bit key making TLSTest failing, so I generated a 2048 bit key locally to verify this tests. I guess maintainers would like to keep their own key in this repository so it's up to them to generate a longer one.
Fixes #877
this part only fixes `Line` type
> pg line type integrity check

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedQueryCommandBaseCodec.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/MSSQLQueriesTest.java
Fixes #1000
If an error occurs while executing a prepared query, the return value may not be present (length = 0 instead of 4).
We must check the actual value length.
> MSSQL PrepExec Return value is not present in case of an error

- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNotNullableDataTypeTest.java
Fixes #1014
Starting from Java 11, LocalDateTime.now() can have microseconds precision.
But the test database defines the test_datetimeoffset column with scale of 5.
Therefore, in order to get consistent behavior between Java 8 and Java 11,
we erase the nanoOfSecond value obtained from the clock with a random number
which has at most tens of microseconds precision.
> Fix testEncodeOffsetDateTime on JDK11

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2ConnectionUriParser.java
- vertx-db2-client/src/test/java/io/vertx/db2client/DB2ConnectionUriParserTest.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLConnectionUriParser.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/impl/MSSQLConnectionUriParserTest.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionUriParser.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/impl/MySQLConnectionUriParserTest.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionUriParser.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectionUriParserTest.java
Signed-off-by: SaberCon <894876785@qq.com>
Motivation:
Most passwords of our postgresql users contains asterisks, which the current `PgConnectionUriParser` fails to parse. So I added the `*` to the `USER_INFO_REGEX` to support the parsing of password containing asterisks.
> Fix asterisk parsing in uri parser

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2RowDesc.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2BinaryDataTypeDecodeTest.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ColumnData.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/protocol/ColumnDefinition.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgColumnDesc.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/desc/ColumnDescriptor.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/RowDesc.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/BinaryDataTypeDecodeTestBase.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/DataTypeTestBase.java
Closes #1020
The type name is client specific.
The feature won't be supported yet on DB2.
> Expose column data type name

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAQueryRequest.java
- vertx-db2-client/src/test/java/io/vertx/db2client/QueryVariationsTest.java
fixes #998
Removes leading comments during the isQuery() check.
> Ignore comments in Queries

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/TdsPacketDecoder.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/TdsSslHandshakeCodec.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/MSSQLQueriesTest.java
A bug in TdsPacketDecoder resulted in IndexOutOfBoundsException.
What happened is that we tried to read the buffer length from the first packet in the buffer instead of the current frame.
Related to https://github.com/eclipse-vertx/vertx-sql-client/issues/1021 and https://github.com/eclipse-vertx/vertx-sql-client/issues/1032
> MSSQL: IndexOutOfBoundsException when a Netty buffer encompasses several TDS Packets

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLConnectionFactory.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLSocketConnection.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/InitCommandCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLCommandCodec.java
Related to #978 
The token value gives the server port and hostname.
On Azure, the hostname may include uppercase letters, consequently we transform it to lowercase (DNS names are case-insensitive).
If we don't, the client will fail to validate the server certificate (which has wildcard SANs using lowercase form).
> Implement redirection with TDS ENV_CHANGE ROUTING token

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/DataType.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLDateTimeDataTypeTest.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLFullDataTypeTestBase.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLNullableDataTypeTestBase.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNotNullableDataTypeTest.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNullableDataTypeTest.java
- vertx-mssql-client/src/test/resources/init.sql
Add support for type datetime (DATETIMN)
Related to https://github.com/eclipse-vertx/vertx-sql-client/issues/1040 and https://github.com/eclipse-vertx/vertx-sql-client/issues/608
> MSSQL: Implement support for type datetime 

- vertx-mssql-client/src/main/asciidoc/index.adoc
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/DataType.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLFullDataTypeTestBase.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLNullableDataTypeTestBase.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNotNullableDataTypeTest.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNullableDataTypeTest.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLSmallDateTimeDataTypeTest.java
- vertx-mssql-client/src/test/resources/init.sql
Add support for smalldatetime.
Apparently MS SQL returns values for columns with smalldatetime as datetime of length 4, so I had to modify the decoding of DATETIMN so it supports data with length 4 to get this to work.
Related #608
> MS SQL: Add support for smalldatetime

- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgCommandCodec.java
```
String sql = "CREATE ROLE x;"
+ "CREATE ROLE y;"
+ "SET ROLE 'x';"
+ "SET ROLE 'y';"
+ "SET ROLE 'x';"
+ "SET ROLE 'y';";
PgPool.pool().withConnection(conn -> conn.query(sql).execute();
```
creates a warning for each `SET ROLE`:
```
WARN  Parameter is_superuser changed to off
WARN  Parameter is_superuser changed to off
WARN  Parameter is_superuser changed to off
WARN  Parameter is_superuser changed to off
```
Reducing the log level from WARN to DEBUG is more appropriate.
If the messages are needed they can easily be enabled by setting
PgCommandCodec log level to DEBUG in the logging configuration.
> Reduce parameter status change log level from WARN to DEBUG

- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleColumnDesc.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/QueryCommand.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/OracleColumnDescriptorTest.java
Fixes #1068
The client must create RowDesc from ResultSet metadata (when possible).
> SqlResult columnDescriptor is always empty for Oracle

- vertx-mysql-client/src/main/asciidoc/index.adoc
Motivation:
Some URLs in https://vertx.io/docs/vertx-mysql-client/java/ are linked to 404.
Conformance:
> Fix 404 urls in MySQL client document

- vertx-oracle-client/src/main/asciidoc/index.adoc
- vertx-oracle-client/src/main/java/examples/OracleClientExamples.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/OracleConnectOptions.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/OraclePool.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleConnectionUriParser.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/impl/InvalidOracleConnectionUriParsingTest.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/impl/ValidOracleConnectionUriParsingTest.java
Closes #1071
This PR adds methods to:
- configure a pool from connection uri
- initialize connection options from uri
In order to avoid confusion, the `jdbc:` prefix is omitted.
> Configure Oracle client from URI

- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/FailureUtil.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/Helper.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/OracleErrorSimpleTest.java
Fixes #1073
When failure is an OracleDatabaseException, it can be simplified using the string format only.
> Sanitize Oracle error messages

- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OracleSimpleQueryTest.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/SimpleQueryTestBase.java
Does not need to override parent class test methods.
The issue was that Oracle does not like the semicolon at the end of the query.
> Simplify OracleSimpleQueryTest

- vertx-db2-client/src/main/java/io/vertx/db2client/DB2ConnectOptions.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2ConnectionUriParser.java
- vertx-db2-client/src/main/java/io/vertx/db2client/spi/DB2Driver.java
- vertx-db2-client/src/test/java/io/vertx/db2client/DB2ConnectionUriParserTest.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/MSSQLConnectOptions.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLConnectionUriParser.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/spi/MSSQLDriver.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/impl/MSSQLConnectionUriParserTest.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnectOptions.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionUriParser.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/spi/MySQLDriver.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/impl/MySQLConnectionUriParserTest.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/OracleConnectOptions.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleConnectionUriParser.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/spi/OracleDriver.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/PgConnectOptions.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionUriParser.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/spi/PgDriver.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectOptionsTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectionUriParserTest.java
- vertx-sql-client-templates/src/test/java/io/vertx/sqlclient/templates/TemplateBuilderTest.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/SqlConnectOptions.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/spi/Driver.java
Improve the usability to allow connection parsing with the drive implementations and json merging, so users can do:
```java
SqlConnectOptions options = SqlConnectOptions.fromUri("postgresql://...").merge(jsonConf); // Will be PgConnectOptions
Pool pool = Pool.create(options); // Will be a PgPool
```
> SqlConnectOptions uri parsing and json merging

- vertx-oracle-client/src/main/asciidoc/index.adoc
fix document typo
typo `ww` to `we`
Motivation:
Found a typo when I tried to translate document to Chinese
> Documentation typo for Connection URI

- vertx-mssql-client/src/main/asciidoc/index.adoc
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLRowImpl.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/DataType.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLDataTypeTestBase.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLFullDataTypeTestBase.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLGuidDataTypeTest.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLNullableDataTypeTestBase.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLPreparedQueryNullableDataTypeTest.java
- vertx-mssql-client/src/test/resources/init.sql
Motivation:
Support for UUID/uniqueidentifier data types in MSSQL.
Our databases make a lot of use of uniqueidentifier columns - without support for them we cannot use vertx-sql-client.
> Support for UUID/uniqueidentifier data types in MSSQL.

- CONTRIBUTING.md
Motivation:
https://github.com/eclipse-vertx/vertx-sql-client/blob/352e8da205598ffd9730ef36891dbc28ff544e53/CONTRIBUTING.md?plain=1#L20
Click the `privately` link will lead to 404. Mailto link can activate the default mail client on the computer for sending an e-mail.
> Add mailto prefix to email address in CONTRIBUTING.md

- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgEncoder.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/ScramClientInitialMessage.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/util/ScramAuthentication.java
Motivation:
`mecanism` -> `mechanism`
Conformance:
> Fix typos in pg-client

- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/pool/SqlConnectionPool.java
Fixes #1148
This is to make sure we never use a deployment context.
> Always use dedicated eventloop context in SqlConnectionPool

- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleColumnDesc.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/OracleQueriesTest.java
Fixes #1124
Oracle returns a int type which does not match `JDBCType.TIMESTAMP_WITH_TIMEZONE` when the column's DB type is `TIMESTAMPZ`.
> Wrong JDBC type for timestampz

- vertx-oracle-client/src/main/java/io/vertx/oracleclient/OracleConnectOptions.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/ServerMode.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleConnectionUriParser.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleDatabaseHelper.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/impl/InvalidOracleConnectionUriParsingTest.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/impl/ValidOracleConnectionUriParsingTest.java
Oracle URL parsing is missing support for EZConnect format (service name / server mode / instance name).
It currently supports service id only (no longer recommended by Oracle)
Also:
- it requires a port to be specified whereas it should be optional
- it accepts user and password separated by slash only whereas other clients take accept colon
> Oracle URL parsing enhancements

- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/junit/MSSQLRule.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/junit/OracleRule.java
The shared instance was started and stopped several times whereas it should happen only once.
> Fix lifecycle bug in MSSQL and Oracle junit rules

- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleConnectionUriParser.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleDatabaseHelper.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/impl/InvalidOracleConnectionUriParsingTest.java
Fixes #1155
The client should fail with a meaningful error message when an unsupported connection format is used, that is:
- LDAP syntax
- Oracle TNS URL
> Fail properly when Oracle url format is not supported

- vertx-oracle-client/src/main/java/io/vertx/oracleclient/OracleException.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/FailureUtil.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/Helper.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/RowReader.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/OracleErrorSimpleTest.java
Closes #1160
This allows users to identify client errors without inspecting the error message.
> Use Oracle specific exception when error occurs in the client

- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/Helper.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/OracleTransactionCommand.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OracleTransactionTest.java
Fixes #1169
The autocommit mode must be re-activated after the transaction completes or fails.
> Oracle Transaction demarcation broken when using OraclePool

- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/CommandHandler.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/Helper.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/OracleBrokenPooledConnectionTest.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OracleConnectionAutoRetryTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/CloseConnectionTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PgClientTestBase.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectionTestBase.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PgPoolTestBase.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PubSubTest.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/ProxyServer.java
Fixes #1173
When the physical connection is broken (connection reset, firewall timeouts, ...etc), the Oracle connection methods throw `SQLExeception` on usage, but there is no way for Vert.x to be notified.
The fix consists in inspecting failures when a command is scheduled on the connection.
If the failure is fatal, then the underlying connection is closed.
This leads to eviction for pooled connection.
Commits can be reviewed individually.
> Evict broken Oracle pooled connection

- vertx-mssql-client/src/main/asciidoc/index.adoc
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/CloseCursorCommandCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/CursorData.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedCursorQueryCommandCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedQueryCommandBaseCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLCommandCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLRowDesc.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/QueryCommandBaseCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/RowResultDecoder.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/TdsMessageCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/TdsMessageEncoder.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/tck/MSSQLPreparedQueryTestBase.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/PreparedQueryTestBase.java
Closes #606 
We use static cursors so that we get information about the total number of rows to fetch.
Cursor data is stored in a map at the connection level.
This allows to manage state using the cursor ids generated by the client as keys.
> MSSQL Cursor and Row streaming implementation

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2Codec.java
- vertx-db2-client/src/test/java/io/vertx/db2client/DB2ErrorMessageTest.java
fixes #900 
Signed-off-by: Mark Swatosh <mark.swatosh@gmail.com>
Adds an error message for inflight commands for the DB2 driver. I tried a number of methods to get an automated test working, but for better or worse the DB2 server tends to end connections gracefully.
The added test can be run manually, since it requires using `docker kill`. I don't think it would be worth the added startup time it would introduce to the test buckets to add another db2 container just for the purpose of killing it during the test, to provide this as an automated test.
> Adding DB2 inflight handling and a manual test

- vertx-pg-client/src/main/asciidoc/index.adoc
Motivation:
The connection URI for CockroachDB's DBaaS requires a strange parameter which was not clear to several users how to set on the reactive PostgreSQL client. This change adds a note making it clear how to pass the parameter correctly.
Conformance:
> Added NOTE for CockroachDB DBaaS configuration

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2SocketConnection.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/InitialHandshakeCommandCodec.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/ConnectionMetaData.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/drda/DRDAConnectResponse.java
- vertx-db2-client/src/test/java/io/vertx/db2client/DB2ErrorMessageTest.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2TransactionTest.java
- vertx-db2-client/src/test/resources/init.zos.sql
Fixes #1131 
At some point support for Db2 z/os was broken, this PR reintroduces support by separating the initial handshake request to two packets, using the response from the first packet to determine if we are talking to z/os, and if so switching from EBCDIC to UTF8.
There are 3 tests still failing with Db2/z, which will be addressed in a follow up issue: #1205
> Reintroducing Db2 z/os support

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2RowImpl.java
- vertx-db2-client/src/test/java/io/vertx/db2client/impl/DB2RowImplTest.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLRowImpl.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/impl/MSSQLRowImplTest.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLRowImpl.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/impl/MySQLRowImplTest.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/RowImpl.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/impl/RowImplTest.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/Tuple.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/impl/TupleTest.java
I found something typo mistake in document of method io.vertx.sqlclient.Tuple.get(Class<T> type, int position):
/**
* Get the the at the specified {@code position} and the specified {@code type}.
*
* <p>The type can be one of the types returned by the row (e.g {@code String.class}) or an array
* of the type (e.g {@code String[].class})).
*
* @param type the expected value type
* @param position the value position
* @return the value if the value is not found or null.
*/
default <T> T get(Class<T> type, int position) {
The return statement: @return the value if the value is not found or null. should be: @return the value if the value is found or null. 
And according to document of method  io.vertx.sqlclient.Tuple.get(Class<T> type, int position) the implementation: …
> Fix ClassCastException when get null enum value

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLSocketConnection.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/CommandHandler.java
Otherwise, the callbacks might be invoked in unexpected order
Related to https://github.com/eclipse-vertx/vert.x/issues/4446
> Do not mix Future terminal operations with other operations

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/CursorData.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/ExtendedCursorQueryCommandCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLCommandCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/QueryCommandBaseCodec.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/MSSQLQueriesTest.java
- vertx-mssql-client/src/test/resources/init.sql
Fixes #1220
When using cursors or streaming, the client asks the server to create a cursor for results.
However, in some cases, the server cannot create it and, instead of failing, returns a complete result set at once.
In this PR, the INFO token is parsed to and the error number inspected to determine if the server executed SQL directly.
In this case, the cursor fetch request is skipped and the command is completed immediately after parsing all tokens.
> MSSQL failure when using streaming on non cursor-friendly statements

- vertx-mysql-client/src/main/asciidoc/index.adoc
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/MySQLConnectOptions.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandCodec.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/junit/MySQLRule.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/ProxySQLConnectionTest.java
- vertx-mysql-client/src/test/resources/init.sql
> Fixes to MySQL pipelining

- .github/workflows/ci.yml
- pom.xml
- vertx-oracle-client/README.adoc
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/junit/OracleRule.java
Oracle 18c has [entered end of life on the 30th of June 2021](https://support.oracle.com/knowledge/Oracle%20Database%20Products/742060_1.html).
To minimise risks, and to improve support for 19c [1] and JDK 17 [2], it would be advisable to upgrade to [`gvenzl/oracle-xe 21-slim`](https://hub.docker.com/r/gvenzl/oracle-xe). The reason why I am suggesting `gvenzl/oracle-xe` is because I noticed that's what the current project test-containers are using. Finally, since the existing work was compatible with 21c, it was a quick win, and no further changes were required other than upadting the CI and test container image. (i.e. CI is passing)
[1] Verified by [Client Server Interoperability Support Matrix](https://www.oracle.com/database/technologies/faq-jdbc.html#Q5) that 21c is compatible with …
> Upgrade test Oracle Database to 21c

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/DataType.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data/MSSQLDecimalDataTypeTest.java
See jdbc driver from Microsoft: https://github.com/microsoft/mssql-jdbc/blob/main/src/main/java/com/microsoft/sqlserver/jdbc/Util.java#L190
Motivation:
Some decimal numbers are wrongly converted into BigDecimal type. For example number 2147483648 comes  from DB as following byte stream: [5, 1, 0, 0, 0, -128]. First byte 5 is length, second 1 is sign (positive) and array [0, 0, 0, -128] is a value it self (reverse order). But constructor new BigInteger(bytes) expects two's-complement binary representation. But this is not our case. Two's-complement for our number is  [0, 0, 0, -128, 0]. That is the reason why there has to be used another constructor with the sign and magnitude. Same way as is used in the jdbc driver from microsoft.
Conformance:
You should have signed the Eclipse …
> MSSQL fix converting DB decimal type to java BigDecimal

- vertx-sql-client/src/main/java/io/vertx/sqlclient/Pool.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/SqlConnection.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/TransactionMode.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/TransactionPropagation.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/PoolBase.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/PoolImpl.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlConnectionBase.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/TransactionTestBase.java
Motivation:
Proposed solution to https://github.com/eclipse-vertx/vertx-sql-client/issues/1214 and https://github.com/eclipse-vertx/vertx-sql-client/issues/646
This could probably be improved a great deal, but I've reached a stage with this one where I'd need some more eyes on it.
I'm also struggling with running a lot of the tests, so I am somewhat in the dark on whether or not this has broken anything.
Conformance:
> Create propagatable connection, add Transaction accessor

- vertx-pg-client/pom.xml
- vertx-pg-client/src/main/asciidoc/index.adoc
- vertx-pg-client/src/main/generated/io/vertx/pgclient/PgConnectOptionsConverter.java
- vertx-pg-client/src/main/java/examples/PgClientExamples.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/PgConnectOptions.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionFactory.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgSocketConnection.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/ExtendedQueryCommandCodec.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgCodec.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgEncoder.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PgBouncerTest.java
Level 7 proxies like PgBouncer can load balance queries over several database connections. When doing so prepared statement cannot be cached by the client and special care must be taken to use extended queries. For now we support PgBouncer proxy.
> Add support for level 7 proxies in Postgres

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2ConnectionImpl.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLConnectionImpl.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionImpl.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleConnectionImpl.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionImpl.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectionTestBase.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PgPooledConnectionTest.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlConnectionBase.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/ConnectionTestBase.java
Fixes #1302
After creating an unpooled connection, add it as a close hook to the creating context. Also, in this case, make sure the connection factory is closed after usage.
> Fix memory leak with one-shot connection factories

- vertx-pg-client/src/test/java/io/vertx/pgclient/PgPoolTest.java
- vertx-sql-client/src/main/generated/io/vertx/sqlclient/PoolOptionsConverter.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/PoolOptions.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/PoolImpl.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/pool/SqlConnectionPool.java
Backport of #1298 to 4.x branch
Adds `maxLifetime` to `PoolOptions` and alters `PooledConnection` to honor the maximum lifetime as well as the idle timeout.
Motivation:
A `maxLifetime` option has been added to PoolOptions that determines the maximum amount of time a connection will stay connected; after this amount of time it will be closed at the next eviction check.
The "expiration" naming was changed to "eviction" to represent the more general check that is performed. The idle timeout refreshing was also change to start immediately after connection and update accordingly to make the idle timeout more predictable and match the max life time check.
Conformance:
You should have signed the Eclipse Contributor Agreement as explained in …
> Max lifetime 4.x

- vertx-sql-client-templates/src/main/java/io/vertx/sqlclient/templates/generator/RowMapperGen.java
In vertx-sql-client-templates, the mutiny version of RowMapped autogenerated classes is missing a static singleton INSTANCE (unlike the ParametersMapped ones).
RowMapperGen outputs `@GenIgnore` on the static singleton INSTANCE, which means that it isn't carried over to the mutiny autogenerated code (IIUC). ParametersMapperGen doesn't have this, so its INSTANCE is carried over to mutiny. It is slightly cumbersome to use the mutiny version of the interface generated by RowMapperGen because of this.
RowMapperGen's output looks like:
```
@io.vertx.codegen.annotations.VertxGen
public interface MyClassRowMapper extends io.vertx.sqlclient.templates.RowMapper<MyClassResponse> {
@io.vertx.codegen.annotations.GenIgnore
MyClassRowMapper INSTANCE = new MyClassRowMapper() { };
...
}
```
whereas …
> Keep singleton INSTANCE in mutiny version of RowMapperGen-generated classes

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/CommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandBaseCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/RowResultDecoder.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/datatype/DataType.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/datatype/DataTypeCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/protocol/ColumnDefinition.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/SpatialDataTypeCodecTestBase.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLBinaryDataTypeDecodeTest.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLTextDataTypeDecodeTest.java
Motivation:
This PR reworks the MySQL client data type mapping part, with fixes to #1239 
Modifications:
1. move checking unsigned & binary flags from data type codec to column definition parsing phase which can avoid checking those flags at row value decoding phase for each prepared statement executing and improve some performance
2. add dedicated unsigned 
numeric & binary datatypes to the `DataType` enum so that the data type codec can use them to decode row values
3. make some **changes** to the MySQL JDBCType mapping
FLOAT: JDBCType.REAL-> JDBCType.FLOAT
CHAR,ENUM: JDBCType.VARCHAR -> JDBCType.CHAR
BINARY: JDBCType.VARCHAR -> JDBCType.BINARY
VARBINARY: JDBCType.VARCHAR -> JDBCType.VARBINARY
TINY_TEXT: JDBCType.BLOB -> JDBCType.CLOB
TEXT: JDBCType.BLOB -> JDBCType.CLOB
MEDIUM_TEXT: …
> MySQL client data type mapping rework - fixes #1239

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/CommandCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ExtendedQueryCommandBaseCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/RowResultDecoder.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/datatype/DataType.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/datatype/DataTypeCodec.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/protocol/ColumnDefinition.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/data/SpatialDataTypeCodecTestBase.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLBinaryDataTypeDecodeTest.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLTextDataTypeDecodeTest.java
backport of https://github.com/eclipse-vertx/vertx-sql-client/pull/1339 to `4.x`
> MySQL client data type mapping rework backport to 4.x

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLDatabaseMetadata.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLServerVersionParserTest.java
Motivation:
Since using mariadb version 11.0.2 i always get parsing exceptions copied below
This commit keeps the old parsing intact but falls back to a method similar to mysql if the mariadb version does not have the `5.5.5-` prefix
```
WARN  i.v.m.i.MySQLDatabaseMetadata [vert.x-eventloop-thread-3] - Incorrect parsing server version tokens
java.lang.NumberFormatException: For input string: ""
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:675)
at java.base/java.lang.Integer.parseInt(Integer.java:781)
at io.vertx.mysqlclient.impl.MySQLDatabaseMetadata.parse(MySQLDatabaseMetadata.java:57)
at io.vertx.mysqlclient.impl.codec.InitialHandshakeCommandCodec.handleInitialHandshake(InitialHandshakeComm …
```
> Allow version parsing for mariadb 11 and above

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLDatabaseMetadata.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLServerVersionParserTest.java
> Allow version parsing for mariadb 11 and above (vertx 4.x)

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2SocketConnection.java
- vertx-db2-client/src/test/java/io/vertx/db2client/tck/DB2TracingTest.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLSocketConnection.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/tck/MSSQLTracingTest.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLDatabaseMetadata.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLSocketConnection.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/tck/MySQLTracingTest.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleJdbcConnection.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OracleTracingTest.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgSocketConnection.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgTracingTest.java
- vertx-sql-client/src/main/asciidoc/tracing.adoc
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/Connection.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/pool/SqlConnectionPool.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/tracing/QueryReporter.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/TracingTestBase.java
See https://github.com/eclipse-vertx/vertx-tracing/issues/64
The specification requires `db.system` span attribute to be present, with a default value of `other_sql`.
The database connection implemented have been changed to report a specific system value (static or computed from database metadata).
> db.system is a mandatory OTEL span attribute

- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgParamDesc.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgPreparedQueryTestBase.java
See #1142
When the number of params exceeds the limit, Postgres successfully prepares the query but returns a number of expected equal to (actual - max - 1).
Then the client reports a strange message like:
"The number of parameters to execute should be consistent with the expected number of parameters = [64464] but the actual number is [130000]."
With this change, an explicit error message is reported.
> Pg Client: fail cleanly when number of params exceeds limit

- vertx-pg-client/src/main/asciidoc/index.adoc
Changed "Command pipeling" to "Command pipelining"
> Fix typo in index.adoc

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/QueryCommandBaseCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/RowResultDecoder.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/RowDecoder.java
The MSSQL row decoder bypasses the decoder flow since handling a row might produce no row. We would like to have the same flow to be used.
The row decoder handleRow method now checks if the returned row is not null before passing it to the collector. In addition we need to use a specific mode to let the mssql decoder which decoding it should use dynamically.
> MSSQL row decoder flow alignment

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2RowImpl.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/RowResultDecoder.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLRowImpl.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/RowResultDecoder.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLRowImpl.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLDecoder.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/RowResultDecoder.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleRow.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OracleCollectorTest.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/RowImpl.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/RowResultDecoder.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/Row.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/RowBase.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/RowDecoder.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/RowInternal.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/CollectorTestBase.java
When using a collector query, allow to recycle the row if that has been already consumed and the decoder can reuse it.
> Add row recycling in collector

- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataTypeCodec.java
Due to a change in JDK 22, the root locale shall not be used anymore for parsing PostgreSQL timestamp, instead US locale should be used.
> Use US locale to parse PostgreSQL timestamps

- vertx-pg-client/src/test/java/io/vertx/pgclient/RowTest.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/Utils.java
See #1323
Convert the temporal value to String using the same formatter as JsonObject.
Then the value can always be read from Json as Instant, even when some parts are missing (hours, minutes, seconds...)
> Fix temporal conversion for Json objects

- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgDecoder.java
fixes #1401 and adds handling for 57P05: idle-session timeout.
> PgClient: Handle idle-session timeout and prevent NullPointerException in PgDecoder.decoderError()

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLSocketConnection.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ClearCachedStatementsEvent.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/ResetConnectionCommandCodec.java
- vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLUtilityCommandTest.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/cache/LruCache.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/cache/PreparedStatementCache.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/impl/LruCacheTest.java
See #1424
Otherwise, the client emits an error such as:
```
io.vertx.mysqlclient.MySQLException: {errorMessage=Unknown prepared statement handler (1) given to mysql_stmt_precheck, errorCode=1243, sqlState=HY000}
```
> Clear MySQL prepared statements cache on connection reset

- vertx-pg-client/pom.xml
- vertx-pg-client/src/main/asciidoc/index.adoc
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/InitCommandCodec.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgEncoder.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/util/ScramAuthentication.java
Motivation:
This update the SCRAM dependency to version 3.0 and also add support channel binding in scram negotiation.
Conformance:
Fixes #1430
> Update SCRAM dependency to 3.0 and support channel binding

- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLConnectionFactory.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLSocketConnection.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLCommandCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/TdsMessageCodec.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/TdsMessageEncoder.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/MSSQLEncryptionTest.java
See #1433
When TLS fragments are bigger than the negotiated TDS packet size, the server may close the connection abruptly.
On TLS fragments see https://datatracker.ietf.org/doc/html/rfc5246#section-6.2.1
> Align TLS fragments size with negotiated TDS packet size

- .github/workflows/ci-4.x.yml
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2ConnectionFactory.java
- vertx-db2-client/src/main/java/io/vertx/db2client/spi/DB2Driver.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/MSSQLConnectionFactory.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/spi/MSSQLDriver.java
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/tck/MSSQLMetricsTest.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLConnectionFactory.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/spi/MySQLDriver.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleConnectionFactory.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/spi/OracleDriver.java
- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OracleMetricsTest.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionFactory.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/spi/PgDriver.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PgMetricsTest.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/ConnectionFactoryBase.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/PoolImpl.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/metrics/ClientMetricsProvider.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/metrics/ClientMetricsWrapper.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/metrics/DynamicClientMetricsProvider.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/metrics/SingleServerClientMetricsProvider.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/pool/SqlConnectionPool.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/spi/ConnectionFactory.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/MetricsTestBase.java
The pool implementation does not actually log queue metrics to the client metrics SPI.
This updates the implementation to actually log queue metrics to the client SPI when the pool uses a fixed connect options (the reason is that the client metrics SPI is coupled to the socket address of the client and most likely this should be changed in Vert.x 5)
> Queue metrics for single address connection pool

- vertx-pg-client/pom.xml
- vertx-pg-client/src/main/asciidoc/index.adoc
Motivation:
Update the scram-client dependency to the latest version.
Conformance:
> Update scram-client to 3.1

- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleJdbcConnection.java
> Oracle: Lightweight Connection Validation

- .github/workflows/ci-4.x.yml
- vertx-mssql-client/docker/docker-compose.yml
- vertx-mssql-client/docker/initdb.sh
- vertx-mssql-client/src/test/java/io/vertx/mssqlclient/junit/MSSQLRule.java
Similar to https://github.com/eclipse-vertx/vertx-sql-client/pull/1457
> Re-enable MSSQL in CI (4.x)

- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgCommandCodec.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgDecoder.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PubSubTest.java
See #1442
This may happen if the connection is used by a PgSubscriber.
> NPE in PgDecoder if a notice is raised while no query is being executed

- vertx-pg-client/pom.xml
- vertx-pg-client/src/main/asciidoc/index.adoc
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/auth/scram/ScramAuthentication.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/auth/scram/ScramSession.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/auth/scram/ScramSessionImpl.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/InitCommandCodec.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/it/MissingScramTest.java
Motivation:
The scram dependency is optional and the module descriptor declares it as static, however in practice when the scram dependency is not available the client cannot be used because the ScramAuthentication is unavailable due to a classloading error. The client should be resilient to this common case and continue to work when scram is not available.
Changes:
Introduce an indirection level, the scram interactions are now handled by a ScramSession and the ScramAuthentication is a factory for sessions. When the scram dependency is not available the ScramAuthentication instance is null, the InitCommandCodec can check this field and throw an exception that will close the connection (as per the protocol requirements).
Result:
The client runs fine without the scram dependency on the …
> Let the client run fine when the scram dependency is not available

- vertx-pg-client/pom.xml
- vertx-pg-client/src/main/java/io/vertx/pgclient/data/Interval.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataTypeCodec.java
- vertx-pg-client/src/test/assembly/benchmarks.xml
- vertx-pg-client/src/test/java/io/vertx/pgclient/benchmarks/IntervalBenchmarks.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/DataTypeTestBase.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/DateTimeTypesExtendedCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/DateTimeTypesSimpleCodecTest.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/IntervalTest.java
Faster and garbage-free codec, compatibility with `java.time.Duration`
Closes #1281
Commits can be reviewed individually.
> Pg Client: improve Interval support

- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataType.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgParamDesc.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/PreparedStatementTest.java
Fixes #1463
With this change, a DataType always has a param extractor. The default extractor signals the failure to convert to PgParamDesc.
> Pg Client might convert a query param to NULL if it has the wrong type

- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OracleConnectionTest.java
Disabled for Oracle because we frequently get ORA-12516 Cannot connect to database
See https://docs.oracle.com/en/error-help/db/ora-12516/?r=23ai
Probable cause is that the service handler gets in a blocked state and is not accepting new connections.
> Disable OracleConnectionTest#testConnectNoLeak tests

- vertx-db2-client/pom.xml
- vertx-mysql-client/pom.xml
- vertx-oracle-client/pom.xml
Probably leftovers when content was copied from the Pg client POM file.
> Remove redundant excludes from Oracle, MySQL surefire and DB2 configs

- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OracleConnectionTest.java
Disabled for Oracle because we frequently get ORA-12516 Cannot connect to database
See https://docs.oracle.com/en/error-help/db/ora-12516/?r=23ai
Probable cause is that the service handler gets in a blocked state and is not accepting new connections.
> Disable OracleConnectionTest#testConnectNoLeak tests (4.x)

- vertx-oracle-client/src/test/java/io/vertx/oracleclient/test/tck/OracleConnectionTest.java
- vertx-sql-client/src/test/java/io/vertx/sqlclient/tck/ConnectionTestBase.java
See individual commits for details
> Re enable no leak oracle tests

- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataType.java
- vertx-pg-client/src/test/java/io/vertx/pgclient/data/PreparedStatementParamCoercionTest.java
Fixes #1477
This is a regression introduced in #1464
When the value is null, the extractor throws a failure. Then, in `ErrorMessageFactory.buildWhenArgumentsTypeNotMatched`, a NPE is thrown because the value of the class cannot be determined.
> PgClient: NPE when inserting null param with default param extractor

- vertx-pg-client/pom.xml
- vertx-pg-client/src/test/java/io/vertx/pgclient/junit/ContainerPgRule.java
- vertx-sql-client-templates/pom.xml
- vertx-sql-client-templates/src/test/java/io/vertx/sqlclient/templates/PgTemplateTestBase.java
For Postgres, we are still using DB specific test containers. These containers require the corresponding JDBC driver.
With this change, we get rid of the JDBC drivers transitive test dependency.
> Switch to generic test containers

- vertx-sql-client-templates/pom.xml
- vertx-sql-client-templates/src/main/java/module-info.java
- vertx-sql-client-templates/src/test/java/module-info.java
Motivation:
The sql templates module does require strictly the codegen modules. These modules are only needed for the code generation phase.
Changes:
Set codegen and java.compiler module requirement to be static, so they are not required when using generated templates at runtime.
> Set the codegen modules requires to static.

- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/RowReader.java
- vertx-oracle-client/src/test/java/tests/oracleclient/OracleBinaryDataTypesTest.java
Motivation:
At least version 4.5.13 has this issue
I encountered an exception while using vertx-oracle stream API to fetch data from a RAW column.
There is no issue with the regular "Prepared queries" API
The stack trace is:
```
Caused by: java.sql.SQLException: ORA-17282: Class argument to getObject is null.
https://docs.oracle.com/error-help/db/ora-17282/
at oracle.jdbc.driver.Accessor.getObject(Accessor.java:1043)
at oracle.jdbc.driver.OracleStatement.getObject(OracleStatement.java:7407)
at oracle.jdbc.driver.InsensitiveScrollableResultSet$RowPublisher$ExpiringRow.getObject(InsensitiveScrollableResultSet.java:1487)
at io.vertx.oracleclient.impl.RowReader.transform(RowReader.java:182)
at io.vertx.oracleclient.impl.RowReader.apply(RowReader.java:173)
at …
```
> simple fix of oracle stream API for RAW column

- vertx-sql-client/src/main/java/io/vertx/sqlclient/PoolOptions.java
> PoolOptions copy constructor doesn't copy all fields

- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/MySQLRowImpl.java
- vertx-mysql-client/src/test/java/io/vertx/tests/mysqlclient/data/NumericDataTypeTest.java
See #1473
Since it is possible to retrieve a `BigDecimal` with `getBigDecimal(idx)`, it should be possible to it as well with `get(BigDecimal.class, idx)`.
> MySQL: Unsupported type java.math.BigDecimal

- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgCodec.java
- vertx-pg-client/src/test/java/io/vertx/tests/pgclient/CloseConnectionTest.java
`PgCodec` tries to fail a command in progress by firing a failure message through the Netty pipeline. This raise issues when there is a read in progress with reentrancy, while this issue should be also addressed in vertx core, proceeding this way means caring about the channel `read`/`readComplete` status to eventually emit a `readComplete` to respect the Netty inbound message protocol.
Instead we can simply fail the handler associated with the codec yielding the same result.
> Improve eager command failure in PostgreSQL client

- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/RowImpl.java
- vertx-pg-client/src/test/java/io/vertx/tests/pgclient/data/ExtendedQueryDataTypeCodecTestBase.java
- vertx-pg-client/src/test/java/io/vertx/tests/pgclient/data/NumericTypesExtendedCodecTest.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/Tuple.java
Fixes the same problem which is described in the #1473 , but for the postgres implementation
> Pg Client: BigDecimal support for reading numeric values

- vertx-db2-client/src/main/java/io/vertx/db2client/DB2ConnectOptions.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/MSSQLConnectOptions.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/OracleConnectOptions.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/PgConnectOptions.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/SqlConnectOptions.java
- vertx-sql-client/src/test/java/io/vertx/tests/sqlclient/tck/ConnectionAutoRetryTestBase.java
`SqlConnectOptions` defaults are initialized properly:
- the default values should all be set in the `init` method
- default values for reconnect attempts and interval are not set
Also, all vendor-specific options (except for MySQL) miss the call to `init` in the parent options.
> Fix connection options initialization

- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleJdbcConnection.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgSocketConnection.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/PreparedStatementImpl.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/QueryExecutor.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/QueryResultBuilder.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SocketConnectionBase.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/TransactionImpl.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/pool/SqlConnectionPool.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/tracing/QueryReporter.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/internal/SqlClientBase.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/internal/SqlConnectionBase.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/internal/command/CommandScheduler.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/internal/command/CompositeCommand.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/internal/pool/PoolImpl.java
Motivation:
The command response flow uses a futures that piggies back to the query result builder and then completes the overall result promise.
Only the terminal node needs to be a promise/future as we are always on the same connection context.
The internal command response flow can uses instead a `Completable` flow that is much more straightforward for debugging and saves un-necessary method calls.
Changes:
Use a `Completable` response flow internally instead of the `Promise` based flow.
> Simplify and optimize the command response future/promise flow

- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2ParamDesc.java
- vertx-db2-client/src/main/java/io/vertx/db2client/impl/codec/DB2PreparedStatement.java
- vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/MSSQLPreparedStatement.java
- vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/MySQLPreparedStatement.java
- vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/commands/OraclePreparedStatement.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/Bind.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/ClosePortalMessage.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/ClosePreparedStatementMessage.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataType.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataTypeCodec.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataTypeEstimator.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/Describe.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/ExecuteMessage.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/OutboundMessage.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/ParamExtractor.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/ParseMessage.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PasswordMessage.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgEncoder.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgParamDesc.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgPreparedStatement.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/Query.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/ScramClientFinalMessage.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/ScramClientInitialMessage.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/StartupMessage.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/SyncMessage.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/TerminateMessage.java
- vertx-pg-client/src/main/java/io/vertx/pgclient/impl/util/Util.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/QueryExecutor.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/internal/PreparedStatement.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/internal/command/ExtendedQueryCommand.java
Motivation:
The pg encoder allocates Netty buffer without an initial capacity, when pipelining is used this buffer can be reallocated multiple times and in agressive scenario can lead to out of memory errors with the adapative allocator.
Changes:
Cumulate and encode all the outbound messages at once when flush happens instead of cumulating them in the outbound buffer.
Capacity is estimated when a message is enqueued.
At flush time, a single buffer of the estimated capacity is created and the outbound messages are written to this buffer.
This requires to pre-render some messages to estimate their length, e.g. a json object is pre-rendered to a string that can be then estimated. The client has been modified to handle message preparation which takes care of this and lazy duplicate the tuple …
> Let the vertx-pg-client encoder estimate the capacity of buffer it allocates

- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SocketConnectionBase.java
Motivation:
When the socket uses pipeling and there are pending messages (due to pipelining limit), the pending message queue will likely be examined for sending by each message read.
Examining the pending message queue is more efficient when done upon channel read complete.
Changes:
Move the pending message check in the read completion event, rather that after each processed messsage.
> Use the channel read complete event to process pending messages.

- vertx-sql-client/src/main/java/io/vertx/sqlclient/RowSet.java
Motivation:
`RowSet` extends `Iterable` to provide iterations over the rows contained in the set.
We should support returning a `java.util.stream.Stream` as well.
Changes:
Add a `stream()` default method to `RowSet` that returns a `java.util.stream.Stream`.
> Provide a RowSet#stream()

- vertx-sql-client/src/main/java/io/vertx/sqlclient/RowSet.java
Motivation:
`RowSet` extends `Iterable` to provide iterations over the rows contained in the set.
We should support returning a `java.util.stream.Stream` as well.
Changes:
Add a `stream()` default method to `RowSet` that returns a `java.util.stream.Stream`.
> Rowset should provide stream 4.

- vertx-sql-client/src/main/java/io/vertx/sqlclient/Pool.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/TransactionPropagationLocal.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/internal/pool/PoolImpl.java
- vertx-sql-client/src/main/java/module-info.java
- vertx-sql-client/src/main/resources/META-INF/services/io.vertx.core.spi.VertxServiceProvider
Motivation:
Context local map usage is discouraged with Vert.x 5 in favor of context local keys.
Changes:
Use context local keys instead of context local map.
> Remove usage of context local map

- vertx-oracle-client/src/test/java/tests/oracleclient/tck/OracleMetricsTest.java
- vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/pool/SqlConnectionPool.java
- vertx-sql-client/src/test/java/io/vertx/tests/sqlclient/tck/MetricsTestBase.java
See #1494
`SqlConnectionPool` must invoke `dequeueMetric` when a connection fails to be acquired
> Metrics vertx_pool_queue_pending doesn't decrease after connection loss

- vertx-sql-client-templates/src/main/asciidoc/index.adoc
- fix gradle build setup
- package info file is required
> Improve documentation for templates code generation
